// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// BatchStockServiceInterface is an autogenerated mock type for the BatchStockServiceInterface type
type BatchStockServiceInterface struct {
	mock.Mock
}

// DeductStockFIFO provides a mock function with given fields: ctx, productID, storeID, qty
func (_m *BatchStockServiceInterface) DeductStockFIFO(ctx context.Context, productID string, storeID string, qty float64) error {
	ret := _m.Called(ctx, productID, storeID, qty)

	if len(ret) == 0 {
		panic("no return value specified for DeductStockFIFO")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) error); ok {
		r0 = rf(ctx, productID, storeID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBatchesByProduct provides a mock function with given fields: ctx, productID, storeID
func (_m *BatchStockServiceInterface) GetBatchesByProduct(ctx context.Context, productID string, storeID string) ([]*domain.StockBatch, error) {
	ret := _m.Called(ctx, productID, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchesByProduct")
	}

	var r0 []*domain.StockBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*domain.StockBatch, error)); ok {
		return rf(ctx, productID, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*domain.StockBatch); ok {
		r0 = rf(ctx, productID, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StockBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, productID, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBatchesByStore provides a mock function with given fields: ctx, f
func (_m *BatchStockServiceInterface) GetBatchesByStore(ctx context.Context, f dto.BatchListFilter) ([]*domain.StockBatch, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchesByStore")
	}

	var r0 []*domain.StockBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.BatchListFilter) ([]*domain.StockBatch, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.BatchListFilter) []*domain.StockBatch); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StockBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.BatchListFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockSummary provides a mock function with given fields: ctx, storeID
func (_m *BatchStockServiceInterface) GetStockSummary(ctx context.Context, storeID string) ([]*domain.BatchStockSummary, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetStockSummary")
	}

	var r0 []*domain.BatchStockSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.BatchStockSummary, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.BatchStockSummary); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.BatchStockSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceivePurchaseOrder provides a mock function with given fields: ctx, poID, storeID, items
func (_m *BatchStockServiceInterface) ReceivePurchaseOrder(ctx context.Context, poID string, storeID string, items []dto.POBatchItem) error {
	ret := _m.Called(ctx, poID, storeID, items)

	if len(ret) == 0 {
		panic("no return value specified for ReceivePurchaseOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []dto.POBatchItem) error); ok {
		r0 = rf(ctx, poID, storeID, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBatchStockServiceInterface creates a new instance of BatchStockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchStockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchStockServiceInterface {
	mock := &BatchStockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
