// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// CustomerServiceInterface is an autogenerated mock type for the CustomerServiceInterface type
type CustomerServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, storeID, req
func (_m *CustomerServiceInterface) Create(ctx context.Context, storeID string, req dto.CreateCustomerRequest) (*dto.CustomerResponse, error) {
	ret := _m.Called(ctx, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.CustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.CreateCustomerRequest) (*dto.CustomerResponse, error)); ok {
		return rf(ctx, storeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.CreateCustomerRequest) *dto.CustomerResponse); ok {
		r0 = rf(ctx, storeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.CreateCustomerRequest) error); ok {
		r1 = rf(ctx, storeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CustomerServiceInterface) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *CustomerServiceInterface) Get(ctx context.Context, id string) (*dto.CustomerResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.CustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.CustomerResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.CustomerResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, f
func (_m *CustomerServiceInterface) List(ctx context.Context, f dto.CustomerListFilter) ([]*dto.CustomerResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*dto.CustomerResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CustomerListFilter) ([]*dto.CustomerResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CustomerListFilter) []*dto.CustomerResponse); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.CustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CustomerListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.CustomerListFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Search provides a mock function with given fields: ctx, f
func (_m *CustomerServiceInterface) Search(ctx context.Context, f dto.CustomerListFilter) ([]*dto.CustomerResponse, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*dto.CustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CustomerListFilter) ([]*dto.CustomerResponse, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CustomerListFilter) []*dto.CustomerResponse); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.CustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CustomerListFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *CustomerServiceInterface) Update(ctx context.Context, id string, req dto.UpdateCustomerRequest) (*dto.CustomerResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.CustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.UpdateCustomerRequest) (*dto.CustomerResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.UpdateCustomerRequest) *dto.CustomerResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.UpdateCustomerRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerServiceInterface creates a new instance of CustomerServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerServiceInterface {
	mock := &CustomerServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
