// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// IncomeServiceInterface is an autogenerated mock type for the IncomeServiceInterface type
type IncomeServiceInterface struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, req
func (_m *IncomeServiceInterface) CreateCategory(ctx context.Context, req *dto.CreateIncomeCategoryRequest) (*dto.IncomeCategoryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *dto.IncomeCategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateIncomeCategoryRequest) (*dto.IncomeCategoryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateIncomeCategoryRequest) *dto.IncomeCategoryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.IncomeCategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateIncomeCategoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateIncome provides a mock function with given fields: ctx, storeID, userID, req
func (_m *IncomeServiceInterface) CreateIncome(ctx context.Context, storeID string, userID string, req *dto.CreateIncomeRequest) (*dto.IncomeResponse, error) {
	ret := _m.Called(ctx, storeID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateIncome")
	}

	var r0 *dto.IncomeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CreateIncomeRequest) (*dto.IncomeResponse, error)); ok {
		return rf(ctx, storeID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CreateIncomeRequest) *dto.IncomeResponse); ok {
		r0 = rf(ctx, storeID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.IncomeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.CreateIncomeRequest) error); ok {
		r1 = rf(ctx, storeID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteIncome provides a mock function with given fields: ctx, id, storeID
func (_m *IncomeServiceInterface) DeleteIncome(ctx context.Context, id string, storeID string) error {
	ret := _m.Called(ctx, id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIncome")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, storeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListCategories provides a mock function with given fields: ctx, includeDeleted
func (_m *IncomeServiceInterface) ListCategories(ctx context.Context, includeDeleted bool) ([]*dto.IncomeCategoryResponse, error) {
	ret := _m.Called(ctx, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []*dto.IncomeCategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]*dto.IncomeCategoryResponse, error)); ok {
		return rf(ctx, includeDeleted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []*dto.IncomeCategoryResponse); ok {
		r0 = rf(ctx, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.IncomeCategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListIncomes provides a mock function with given fields: ctx, f
func (_m *IncomeServiceInterface) ListIncomes(ctx context.Context, f dto.IncomeListFilter) ([]*dto.IncomeResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for ListIncomes")
	}

	var r0 []*dto.IncomeResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.IncomeListFilter) ([]*dto.IncomeResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.IncomeListFilter) []*dto.IncomeResponse); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.IncomeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.IncomeListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.IncomeListFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SoftDeleteCategory provides a mock function with given fields: ctx, id
func (_m *IncomeServiceInterface) SoftDeleteCategory(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCategory provides a mock function with given fields: ctx, id, req
func (_m *IncomeServiceInterface) UpdateCategory(ctx context.Context, id string, req *dto.UpdateIncomeCategoryRequest) (*dto.IncomeCategoryResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 *dto.IncomeCategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateIncomeCategoryRequest) (*dto.IncomeCategoryResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateIncomeCategoryRequest) *dto.IncomeCategoryResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.IncomeCategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateIncomeCategoryRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateIncome provides a mock function with given fields: ctx, id, storeID, req
func (_m *IncomeServiceInterface) UpdateIncome(ctx context.Context, id string, storeID string, req *dto.UpdateIncomeRequest) (*dto.IncomeResponse, error) {
	ret := _m.Called(ctx, id, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIncome")
	}

	var r0 *dto.IncomeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateIncomeRequest) (*dto.IncomeResponse, error)); ok {
		return rf(ctx, id, storeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateIncomeRequest) *dto.IncomeResponse); ok {
		r0 = rf(ctx, id, storeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.IncomeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.UpdateIncomeRequest) error); ok {
		r1 = rf(ctx, id, storeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIncomeServiceInterface creates a new instance of IncomeServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIncomeServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *IncomeServiceInterface {
	mock := &IncomeServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
