// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// LoyaltyServiceInterface is an autogenerated mock type for the LoyaltyServiceInterface type
type LoyaltyServiceInterface struct {
	mock.Mock
}

// AssignTier provides a mock function with given fields: ctx, customerID, tierID
func (_m *LoyaltyServiceInterface) AssignTier(ctx context.Context, customerID string, tierID string) error {
	ret := _m.Called(ctx, customerID, tierID)

	if len(ret) == 0 {
		panic("no return value specified for AssignTier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, customerID, tierID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EarnPoints provides a mock function with given fields: ctx, storeID, customerID, transactionID, total
func (_m *LoyaltyServiceInterface) EarnPoints(ctx context.Context, storeID string, customerID string, transactionID *string, total float64) (*dto.LoyaltyLedgerResponse, error) {
	ret := _m.Called(ctx, storeID, customerID, transactionID, total)

	if len(ret) == 0 {
		panic("no return value specified for EarnPoints")
	}

	var r0 *dto.LoyaltyLedgerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, float64) (*dto.LoyaltyLedgerResponse, error)); ok {
		return rf(ctx, storeID, customerID, transactionID, total)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, float64) *dto.LoyaltyLedgerResponse); ok {
		r0 = rf(ctx, storeID, customerID, transactionID, total)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoyaltyLedgerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string, float64) error); ok {
		r1 = rf(ctx, storeID, customerID, transactionID, total)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBalance provides a mock function with given fields: ctx, customerID
func (_m *LoyaltyServiceInterface) GetBalance(ctx context.Context, customerID string) (*dto.LoyaltyBalanceResponse, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *dto.LoyaltyBalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.LoyaltyBalanceResponse, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.LoyaltyBalanceResponse); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoyaltyBalanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields: ctx, customerID
func (_m *LoyaltyServiceInterface) GetHistory(ctx context.Context, customerID string) ([]*dto.LoyaltyLedgerResponse, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []*dto.LoyaltyLedgerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.LoyaltyLedgerResponse, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.LoyaltyLedgerResponse); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.LoyaltyLedgerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistoryPaginated provides a mock function with given fields: ctx, customerID, page, perPage
func (_m *LoyaltyServiceInterface) GetHistoryPaginated(ctx context.Context, customerID string, page int, perPage int) ([]*dto.LoyaltyLedgerResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, customerID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryPaginated")
	}

	var r0 []*dto.LoyaltyLedgerResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*dto.LoyaltyLedgerResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, customerID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*dto.LoyaltyLedgerResponse); ok {
		r0 = rf(ctx, customerID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.LoyaltyLedgerResponse)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) dto.PaginationMeta); ok {
		r1 = rf(ctx, customerID, page, perPage)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}
	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, customerID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// VoidTransactionPoints provides a mock function with given fields: ctx, customerID, transactionID, originalPoints
func (_m *LoyaltyServiceInterface) VoidTransactionPoints(ctx context.Context, customerID string, transactionID *string, originalPoints float64) error {
	ret := _m.Called(ctx, customerID, transactionID, originalPoints)

	if len(ret) == 0 {
		panic("no return value specified for VoidTransactionPoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, float64) error); ok {
		r0 = rf(ctx, customerID, transactionID, originalPoints)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdjustPoints provides a mock function with given fields: ctx, customerID, delta, note
func (_m *LoyaltyServiceInterface) AdjustPoints(ctx context.Context, customerID string, delta float64, note string) (*dto.LoyaltyLedgerResponse, error) {
	ret := _m.Called(ctx, customerID, delta, note)

	if len(ret) == 0 {
		panic("no return value specified for AdjustPoints")
	}

	var r0 *dto.LoyaltyLedgerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, string) (*dto.LoyaltyLedgerResponse, error)); ok {
		return rf(ctx, customerID, delta, note)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, string) *dto.LoyaltyLedgerResponse); ok {
		r0 = rf(ctx, customerID, delta, note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoyaltyLedgerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64, string) error); ok {
		r1 = rf(ctx, customerID, delta, note)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTiers provides a mock function with given fields: ctx
func (_m *LoyaltyServiceInterface) ListTiers(ctx context.Context) ([]*dto.MembershipTierResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTiers")
	}

	var r0 []*dto.MembershipTierResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.MembershipTierResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.MembershipTierResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.MembershipTierResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedeemPoints provides a mock function with given fields: ctx, customerID, transactionID, points
func (_m *LoyaltyServiceInterface) RedeemPoints(ctx context.Context, customerID string, transactionID *string, points float64) (*dto.LoyaltyLedgerResponse, error) {
	ret := _m.Called(ctx, customerID, transactionID, points)

	if len(ret) == 0 {
		panic("no return value specified for RedeemPoints")
	}

	var r0 *dto.LoyaltyLedgerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, float64) (*dto.LoyaltyLedgerResponse, error)); ok {
		return rf(ctx, customerID, transactionID, points)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, float64) *dto.LoyaltyLedgerResponse); ok {
		r0 = rf(ctx, customerID, transactionID, points)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoyaltyLedgerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, float64) error); ok {
		r1 = rf(ctx, customerID, transactionID, points)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoyaltySummary provides a mock function with given fields: ctx, storeID
func (_m *LoyaltyServiceInterface) GetLoyaltySummary(ctx context.Context, storeID string) (*dto.LoyaltySummaryResponse, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetLoyaltySummary")
	}

	var r0 *dto.LoyaltySummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.LoyaltySummaryResponse, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.LoyaltySummaryResponse); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoyaltySummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoyaltyServiceInterface creates a new instance of LoyaltyServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoyaltyServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoyaltyServiceInterface {
	mock := &LoyaltyServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
