// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// PriceHistoryServiceInterface is an autogenerated mock type for the PriceHistoryServiceInterface type
type PriceHistoryServiceInterface struct {
	mock.Mock
}

// ListByProduct provides a mock function with given fields: ctx, productID, f
func (_m *PriceHistoryServiceInterface) ListByProduct(ctx context.Context, productID string, f dto.PriceHistoryFilter) ([]*dto.PriceHistoryRow, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, productID, f)

	if len(ret) == 0 {
		panic("no return value specified for ListByProduct")
	}

	var r0 []*dto.PriceHistoryRow
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.PriceHistoryFilter) ([]*dto.PriceHistoryRow, dto.PaginationMeta, error)); ok {
		return rf(ctx, productID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.PriceHistoryFilter) []*dto.PriceHistoryRow); ok {
		r0 = rf(ctx, productID, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PriceHistoryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.PriceHistoryFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, productID, f)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, dto.PriceHistoryFilter) error); ok {
		r2 = rf(ctx, productID, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListByStore provides a mock function with given fields: ctx, storeID, f
func (_m *PriceHistoryServiceInterface) ListByStore(ctx context.Context, storeID string, f dto.PriceHistoryFilter) ([]*dto.PriceHistoryRow, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, storeID, f)

	if len(ret) == 0 {
		panic("no return value specified for ListByStore")
	}

	var r0 []*dto.PriceHistoryRow
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.PriceHistoryFilter) ([]*dto.PriceHistoryRow, dto.PaginationMeta, error)); ok {
		return rf(ctx, storeID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.PriceHistoryFilter) []*dto.PriceHistoryRow); ok {
		r0 = rf(ctx, storeID, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PriceHistoryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.PriceHistoryFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, storeID, f)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, dto.PriceHistoryFilter) error); ok {
		r2 = rf(ctx, storeID, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RecordChange provides a mock function with given fields: ctx, productID, storeID, changedBy, oldCost, newCost, oldSell, newSell, source, refID, notes
func (_m *PriceHistoryServiceInterface) RecordChange(ctx context.Context, productID string, storeID string, changedBy string, oldCost float64, newCost float64, oldSell float64, newSell float64, source string, refID *string, notes *string) error {
	ret := _m.Called(ctx, productID, storeID, changedBy, oldCost, newCost, oldSell, newSell, source, refID, notes)

	if len(ret) == 0 {
		panic("no return value specified for RecordChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, float64, float64, float64, float64, string, *string, *string) error); ok {
		r0 = rf(ctx, productID, storeID, changedBy, oldCost, newCost, oldSell, newSell, source, refID, notes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPriceHistoryServiceInterface creates a new instance of PriceHistoryServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceHistoryServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceHistoryServiceInterface {
	mock := &PriceHistoryServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
