// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// PurchaseOrderServiceInterface is an autogenerated mock type for the PurchaseOrderServiceInterface type
type PurchaseOrderServiceInterface struct {
	mock.Mock
}

// CancelPO provides a mock function with given fields: ctx, id
func (_m *PurchaseOrderServiceInterface) CancelPO(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelPO")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePO provides a mock function with given fields: ctx, storeID, req, userID
func (_m *PurchaseOrderServiceInterface) CreatePO(ctx context.Context, storeID string, req *dto.CreatePORequest, userID string) (*dto.POResponse, error) {
	ret := _m.Called(ctx, storeID, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePO")
	}

	var r0 *dto.POResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreatePORequest, string) (*dto.POResponse, error)); ok {
		return rf(ctx, storeID, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreatePORequest, string) *dto.POResponse); ok {
		r0 = rf(ctx, storeID, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.POResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.CreatePORequest, string) error); ok {
		r1 = rf(ctx, storeID, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePayment provides a mock function with given fields: ctx, poID, storeID, userID, req
func (_m *PurchaseOrderServiceInterface) CreatePayment(ctx context.Context, poID string, storeID string, userID string, req dto.POPaymentRequest) (*dto.POPaymentResponse, error) {
	ret := _m.Called(ctx, poID, storeID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *dto.POPaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, dto.POPaymentRequest) (*dto.POPaymentResponse, error)); ok {
		return rf(ctx, poID, storeID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, dto.POPaymentRequest) *dto.POPaymentResponse); ok {
		r0 = rf(ctx, poID, storeID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.POPaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, dto.POPaymentRequest) error); ok {
		r1 = rf(ctx, poID, storeID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPO provides a mock function with given fields: ctx, id
func (_m *PurchaseOrderServiceInterface) GetPO(ctx context.Context, id string) (*dto.POResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPO")
	}

	var r0 *dto.POResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.POResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.POResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.POResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPOs provides a mock function with given fields: ctx, filter
func (_m *PurchaseOrderServiceInterface) ListPOs(ctx context.Context, filter dto.POListFilter) ([]*dto.POResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPOs")
	}

	var r0 []*dto.POResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.POListFilter) ([]*dto.POResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.POListFilter) []*dto.POResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.POResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.POListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.POListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListPayments provides a mock function with given fields: ctx, poID
func (_m *PurchaseOrderServiceInterface) ListPayments(ctx context.Context, poID string) ([]*dto.POPaymentResponse, error) {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for ListPayments")
	}

	var r0 []*dto.POPaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.POPaymentResponse, error)); ok {
		return rf(ctx, poID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.POPaymentResponse); ok {
		r0 = rf(ctx, poID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.POPaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayableSummary provides a mock function with given fields: ctx, storeID
func (_m *PurchaseOrderServiceInterface) PayableSummary(ctx context.Context, storeID string) (*dto.PayableSummary, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for PayableSummary")
	}

	var r0 *dto.PayableSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.PayableSummary, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.PayableSummary); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PayableSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceivePO provides a mock function with given fields: ctx, id, userID
func (_m *PurchaseOrderServiceInterface) ReceivePO(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReceivePO")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitPO provides a mock function with given fields: ctx, id, userID
func (_m *PurchaseOrderServiceInterface) SubmitPO(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SubmitPO")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePO provides a mock function with given fields: ctx, id, req, storeID
func (_m *PurchaseOrderServiceInterface) UpdatePO(ctx context.Context, id string, req *dto.UpdatePORequest, storeID string) (*dto.POResponse, error) {
	ret := _m.Called(ctx, id, req, storeID)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePO")
	}

	var r0 *dto.POResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdatePORequest, string) (*dto.POResponse, error)); ok {
		return rf(ctx, id, req, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdatePORequest, string) *dto.POResponse); ok {
		r0 = rf(ctx, id, req, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.POResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdatePORequest, string) error); ok {
		r1 = rf(ctx, id, req, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveSignatures provides a mock function with given fields: ctx, poID, req
func (_m *PurchaseOrderServiceInterface) SaveSignatures(ctx context.Context, poID string, req dto.SaveSignaturesRequest) (*dto.POResponse, error) {
	ret := _m.Called(ctx, poID, req)

	if len(ret) == 0 {
		panic("no return value specified for SaveSignatures")
	}

	var r0 *dto.POResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.SaveSignaturesRequest) (*dto.POResponse, error)); ok {
		return rf(ctx, poID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.SaveSignaturesRequest) *dto.POResponse); ok {
		r0 = rf(ctx, poID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.POResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.SaveSignaturesRequest) error); ok {
		r1 = rf(ctx, poID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPurchaseOrderServiceInterface creates a new instance of PurchaseOrderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPurchaseOrderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PurchaseOrderServiceInterface {
	mock := &PurchaseOrderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
