// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// ExportCSV provides a mock function with given fields: ctx, report, filter
func (_m *ReportServiceInterface) ExportCSV(ctx context.Context, report string, filter dto.ReportFilter) ([]byte, error) {
	ret := _m.Called(ctx, report, filter)

	if len(ret) == 0 {
		panic("no return value specified for ExportCSV")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ReportFilter) ([]byte, error)); ok {
		return rf(ctx, report, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ReportFilter) []byte); ok {
		r0 = rf(ctx, report, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.ReportFilter) error); ok {
		r1 = rf(ctx, report, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExportPDF provides a mock function with given fields: ctx, report, filter
func (_m *ReportServiceInterface) ExportPDF(ctx context.Context, report string, filter dto.ReportFilter) ([]byte, error) {
	ret := _m.Called(ctx, report, filter)

	if len(ret) == 0 {
		panic("no return value specified for ExportPDF")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ReportFilter) ([]byte, error)); ok {
		return rf(ctx, report, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ReportFilter) []byte); ok {
		r0 = rf(ctx, report, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.ReportFilter) error); ok {
		r1 = rf(ctx, report, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportServiceInterface is an autogenerated mock type for the ReportServiceInterface type
type ReportServiceInterface struct {
	mock.Mock
}

// CashFlow provides a mock function with given fields: ctx, filter
func (_m *ReportServiceInterface) CashFlow(ctx context.Context, filter dto.ReportFilter) (*dto.CashFlowResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CashFlow")
	}

	var r0 *dto.CashFlowResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter) (*dto.CashFlowResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter) *dto.CashFlowResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CashFlowResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashFlowDetail provides a mock function with given fields: ctx, storeID, dateStr
func (_m *ReportServiceInterface) CashFlowDetail(ctx context.Context, storeID string, dateStr string) ([]dto.CashFlowDetailEntry, error) {
	ret := _m.Called(ctx, storeID, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for CashFlowDetail")
	}

	var r0 []dto.CashFlowDetailEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]dto.CashFlowDetailEntry, error)); ok {
		return rf(ctx, storeID, dateStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []dto.CashFlowDetailEntry); ok {
		r0 = rf(ctx, storeID, dateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CashFlowDetailEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, storeID, dateStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfitSummary provides a mock function with given fields: ctx, filter, groupBy
func (_m *ReportServiceInterface) ProfitSummary(ctx context.Context, filter dto.ReportFilter, groupBy string) (*dto.ProfitSummaryResponse, error) {
	ret := _m.Called(ctx, filter, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for ProfitSummary")
	}

	var r0 *dto.ProfitSummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter, string) (*dto.ProfitSummaryResponse, error)); ok {
		return rf(ctx, filter, groupBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter, string) *dto.ProfitSummaryResponse); ok {
		r0 = rf(ctx, filter, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProfitSummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportFilter, string) error); ok {
		r1 = rf(ctx, filter, groupBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SalesByCashier provides a mock function with given fields: ctx, filter
func (_m *ReportServiceInterface) SalesByCashier(ctx context.Context, filter dto.ReportFilter) ([]dto.SalesByCashierRow, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SalesByCashier")
	}

	var r0 []dto.SalesByCashierRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter) ([]dto.SalesByCashierRow, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter) []dto.SalesByCashierRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SalesByCashierRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SalesByProduct provides a mock function with given fields: ctx, filter
func (_m *ReportServiceInterface) SalesByProduct(ctx context.Context, filter dto.ReportFilter) ([]dto.SalesByProductRow, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SalesByProduct")
	}

	var r0 []dto.SalesByProductRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter) ([]dto.SalesByProductRow, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter) []dto.SalesByProductRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SalesByProductRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SalesSummary provides a mock function with given fields: ctx, filter
func (_m *ReportServiceInterface) SalesSummary(ctx context.Context, filter dto.ReportFilter) (*dto.SalesSummaryResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SalesSummary")
	}

	var r0 *dto.SalesSummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter) (*dto.SalesSummaryResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportFilter) *dto.SalesSummaryResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SalesSummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StockValuation provides a mock function with given fields: ctx, storeID
func (_m *ReportServiceInterface) StockValuation(ctx context.Context, storeID string) (*dto.StockValuationResponse, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for StockValuation")
	}

	var r0 *dto.StockValuationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.StockValuationResponse, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.StockValuationResponse); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StockValuationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportServiceInterface creates a new instance of ReportServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportServiceInterface {
	mock := &ReportServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
