// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// StockAdjustmentServiceInterface is an autogenerated mock type for the StockAdjustmentServiceInterface type
type StockAdjustmentServiceInterface struct {
	mock.Mock
}

// CreateAdjustment provides a mock function with given fields: ctx, storeID, userID, input
func (_m *StockAdjustmentServiceInterface) CreateAdjustment(ctx context.Context, storeID string, userID string, input domain.CreateAdjustmentInput) error {
	ret := _m.Called(ctx, storeID, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdjustment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.CreateAdjustmentInput) error); ok {
		r0 = rf(ctx, storeID, userID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAdjustmentHistory provides a mock function with given fields: ctx, storeID, productID
func (_m *StockAdjustmentServiceInterface) GetAdjustmentHistory(ctx context.Context, storeID string, productID *string) ([]*domain.StockAdjustment, error) {
	ret := _m.Called(ctx, storeID, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetAdjustmentHistory")
	}

	var r0 []*domain.StockAdjustment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) ([]*domain.StockAdjustment, error)); ok {
		return rf(ctx, storeID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) []*domain.StockAdjustment); ok {
		r0 = rf(ctx, storeID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StockAdjustment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = rf(ctx, storeID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStockAdjustmentServiceInterface creates a new instance of StockAdjustmentServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockAdjustmentServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockAdjustmentServiceInterface {
	mock := &StockAdjustmentServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
