// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// SupplierServiceInterface is an autogenerated mock type for the SupplierServiceInterface type
type SupplierServiceInterface struct {
	mock.Mock
}

// CreateSupplier provides a mock function with given fields: ctx, req
func (_m *SupplierServiceInterface) CreateSupplier(ctx context.Context, req *dto.CreateSupplierRequest) (*dto.SupplierResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSupplier")
	}

	var r0 *dto.SupplierResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateSupplierRequest) (*dto.SupplierResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateSupplierRequest) *dto.SupplierResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SupplierResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateSupplierRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSupplier provides a mock function with given fields: ctx, id
func (_m *SupplierServiceInterface) DeleteSupplier(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSupplier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSupplier provides a mock function with given fields: ctx, id
func (_m *SupplierServiceInterface) GetSupplier(ctx context.Context, id string) (*dto.SupplierResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSupplier")
	}

	var r0 *dto.SupplierResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.SupplierResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.SupplierResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SupplierResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSuppliers provides a mock function with given fields: ctx, filter
func (_m *SupplierServiceInterface) ListSuppliers(ctx context.Context, filter dto.SupplierListFilter) ([]*dto.SupplierResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListSuppliers")
	}

	var r0 []*dto.SupplierResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SupplierListFilter) ([]*dto.SupplierResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SupplierListFilter) []*dto.SupplierResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.SupplierResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SupplierListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.SupplierListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateSupplier provides a mock function with given fields: ctx, id, req
func (_m *SupplierServiceInterface) UpdateSupplier(ctx context.Context, id string, req *dto.UpdateSupplierRequest) (*dto.SupplierResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSupplier")
	}

	var r0 *dto.SupplierResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateSupplierRequest) (*dto.SupplierResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateSupplierRequest) *dto.SupplierResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SupplierResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateSupplierRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSupplierServiceInterface creates a new instance of SupplierServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupplierServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupplierServiceInterface {
	mock := &SupplierServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
