// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// tableRepo is an autogenerated mock type for the tableRepo type
type tableRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, t
func (_m *tableRepo) Create(ctx context.Context, t *domain.RestaurantTable) (*domain.RestaurantTable, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.RestaurantTable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RestaurantTable) (*domain.RestaurantTable, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RestaurantTable) *domain.RestaurantTable); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RestaurantTable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.RestaurantTable) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByStore provides a mock function with given fields: ctx, storeID
func (_m *tableRepo) FindAllByStore(ctx context.Context, storeID string) ([]*domain.RestaurantTable, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByStore")
	}

	var r0 []*domain.RestaurantTable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.RestaurantTable, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.RestaurantTable); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.RestaurantTable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *tableRepo) FindByID(ctx context.Context, id string) (*domain.RestaurantTable, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.RestaurantTable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RestaurantTable, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RestaurantTable); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RestaurantTable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *tableRepo) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, t
func (_m *tableRepo) Update(ctx context.Context, t *domain.RestaurantTable) (*domain.RestaurantTable, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.RestaurantTable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RestaurantTable) (*domain.RestaurantTable, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RestaurantTable) *domain.RestaurantTable); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RestaurantTable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.RestaurantTable) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *tableRepo) UpdateStatus(ctx context.Context, id string, status domain.TableStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TableStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newTableRepo creates a new instance of tableRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTableRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *tableRepo {
	mock := &tableRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
