// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// TransactionServiceInterface is an autogenerated mock type for the TransactionServiceInterface type
type TransactionServiceInterface struct {
	mock.Mock
}

// Checkout provides a mock function with given fields: ctx, storeID, req, cashierID
func (_m *TransactionServiceInterface) Checkout(ctx context.Context, storeID string, req *dto.CreateTransactionRequest, cashierID string) (*dto.TransactionResponse, error) {
	ret := _m.Called(ctx, storeID, req, cashierID)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 *dto.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateTransactionRequest, string) (*dto.TransactionResponse, error)); ok {
		return rf(ctx, storeID, req, cashierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateTransactionRequest, string) *dto.TransactionResponse); ok {
		r0 = rf(ctx, storeID, req, cashierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.CreateTransactionRequest, string) error); ok {
		r1 = rf(ctx, storeID, req, cashierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDraft provides a mock function with given fields: ctx, storeID, cashierID, req
func (_m *TransactionServiceInterface) CreateDraft(ctx context.Context, storeID string, cashierID string, req *dto.CreateDraftRequest) (*dto.TransactionResponse, error) {
	ret := _m.Called(ctx, storeID, cashierID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateDraft")
	}

	var r0 *dto.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CreateDraftRequest) (*dto.TransactionResponse, error)); ok {
		return rf(ctx, storeID, cashierID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CreateDraftRequest) *dto.TransactionResponse); ok {
		r0 = rf(ctx, storeID, cashierID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.CreateDraftRequest) error); ok {
		r1 = rf(ctx, storeID, cashierID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDraftByTable provides a mock function with given fields: ctx, storeID, tableID
func (_m *TransactionServiceInterface) GetDraftByTable(ctx context.Context, storeID string, tableID string) (*dto.TransactionResponse, error) {
	ret := _m.Called(ctx, storeID, tableID)

	if len(ret) == 0 {
		panic("no return value specified for GetDraftByTable")
	}

	var r0 *dto.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.TransactionResponse, error)); ok {
		return rf(ctx, storeID, tableID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.TransactionResponse); ok {
		r0 = rf(ctx, storeID, tableID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, storeID, tableID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKDSTickets provides a mock function with given fields: ctx, storeID
func (_m *TransactionServiceInterface) GetKDSTickets(ctx context.Context, storeID string) ([]*dto.TransactionResponse, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetKDSTickets")
	}

	var r0 []*dto.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.TransactionResponse, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.TransactionResponse); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransaction provides a mock function with given fields: ctx, id
func (_m *TransactionServiceInterface) GetTransaction(ctx context.Context, id string) (*dto.TransactionResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 *dto.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.TransactionResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.TransactionResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTransactions provides a mock function with given fields: ctx, filter
func (_m *TransactionServiceInterface) ListTransactions(ctx context.Context, filter dto.TransactionListFilter) ([]*dto.TransactionResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 []*dto.TransactionResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.TransactionListFilter) ([]*dto.TransactionResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.TransactionListFilter) []*dto.TransactionResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.TransactionListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.TransactionListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PayDraft provides a mock function with given fields: ctx, storeID, txnID, cashierID, req
func (_m *TransactionServiceInterface) PayDraft(ctx context.Context, storeID string, txnID string, cashierID string, req *dto.PayDraftRequest) (*dto.TransactionResponse, error) {
	ret := _m.Called(ctx, storeID, txnID, cashierID, req)

	if len(ret) == 0 {
		panic("no return value specified for PayDraft")
	}

	var r0 *dto.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *dto.PayDraftRequest) (*dto.TransactionResponse, error)); ok {
		return rf(ctx, storeID, txnID, cashierID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *dto.PayDraftRequest) *dto.TransactionResponse); ok {
		r0 = rf(ctx, storeID, txnID, cashierID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *dto.PayDraftRequest) error); ok {
		r1 = rf(ctx, storeID, txnID, cashierID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDraftItems provides a mock function with given fields: ctx, storeID, txnID, req
func (_m *TransactionServiceInterface) UpdateDraftItems(ctx context.Context, storeID string, txnID string, req *dto.UpdateDraftRequest) (*dto.TransactionResponse, error) {
	ret := _m.Called(ctx, storeID, txnID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDraftItems")
	}

	var r0 *dto.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateDraftRequest) (*dto.TransactionResponse, error)); ok {
		return rf(ctx, storeID, txnID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateDraftRequest) *dto.TransactionResponse); ok {
		r0 = rf(ctx, storeID, txnID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.UpdateDraftRequest) error); ok {
		r1 = rf(ctx, storeID, txnID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKDSItemStatus provides a mock function with given fields: ctx, itemID, req
func (_m *TransactionServiceInterface) UpdateKDSItemStatus(ctx context.Context, itemID string, req *dto.UpdateKDSItemStatusRequest) error {
	ret := _m.Called(ctx, itemID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKDSItemStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateKDSItemStatusRequest) error); ok {
		r0 = rf(ctx, itemID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VoidTransaction provides a mock function with given fields: ctx, id, userID
func (_m *TransactionServiceInterface) VoidTransaction(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for VoidTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionServiceInterface creates a new instance of TransactionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionServiceInterface {
	mock := &TransactionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
