// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// UserAdminServiceInterface is an autogenerated mock type for the UserAdminServiceInterface type
type UserAdminServiceInterface struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, req
func (_m *UserAdminServiceInterface) CreateUser(ctx context.Context, req *dto.CreateUserRequest) (*dto.UserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateUserRequest) (*dto.UserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateUserRequest) *dto.UserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateUserRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeactivateUser provides a mock function with given fields: ctx, id
func (_m *UserAdminServiceInterface) DeactivateUser(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *UserAdminServiceInterface) GetUser(ctx context.Context, id string) (*dto.UserResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.UserResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.UserResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRoles provides a mock function with given fields: ctx
func (_m *UserAdminServiceInterface) ListRoles(ctx context.Context) ([]*domain.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []*domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, search, includeInactive, page, perPage
func (_m *UserAdminServiceInterface) ListUsers(ctx context.Context, search string, includeInactive bool, page int, perPage int) ([]dto.UserResponse, int, error) {
	ret := _m.Called(ctx, search, includeInactive, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []dto.UserResponse
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, int, int) ([]dto.UserResponse, int, error)); ok {
		return rf(ctx, search, includeInactive, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, int, int) []dto.UserResponse); ok {
		r0 = rf(ctx, search, includeInactive, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool, int, int) int); ok {
		r1 = rf(ctx, search, includeInactive, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, bool, int, int) error); ok {
		r2 = rf(ctx, search, includeInactive, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResetPassword provides a mock function with given fields: ctx, id, req
func (_m *UserAdminServiceInterface) ResetPassword(ctx context.Context, id string, req *dto.ResetPasswordRequest) error {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.ResetPasswordRequest) error); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUserStores provides a mock function with given fields: ctx, userID, req
func (_m *UserAdminServiceInterface) SetUserStores(ctx context.Context, userID string, req *dto.SetUserStoresRequest) (*dto.UserResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for SetUserStores")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.SetUserStoresRequest) (*dto.UserResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.SetUserStoresRequest) *dto.UserResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.SetUserStoresRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, id, req
func (_m *UserAdminServiceInterface) UpdateUser(ctx context.Context, id string, req *dto.UpdateUserRequest) (*dto.UserResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateUserRequest) (*dto.UserResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateUserRequest) *dto.UserResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateUserRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserAdminServiceInterface creates a new instance of UserAdminServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAdminServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAdminServiceInterface {
	mock := &UserAdminServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
