// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MenuItemServiceInterface is an autogenerated mock type for the MenuItemServiceInterface type
type MenuItemServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, storeID, req
func (_m *MenuItemServiceInterface) Create(ctx context.Context, storeID string, req *dto.CreateMenuItemRequest) (*dto.MenuItemResponse, error) {
	ret := _m.Called(ctx, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.MenuItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateMenuItemRequest) (*dto.MenuItemResponse, error)); ok {
		return rf(ctx, storeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateMenuItemRequest) *dto.MenuItemResponse); ok {
		r0 = rf(ctx, storeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.MenuItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.CreateMenuItemRequest) error); ok {
		r1 = rf(ctx, storeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MenuItemServiceInterface) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, storeID
func (_m *MenuItemServiceInterface) List(ctx context.Context, storeID string) ([]*dto.MenuItemResponse, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*dto.MenuItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.MenuItemResponse, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.MenuItemResponse); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.MenuItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MenuItemServiceInterface) Update(ctx context.Context, id string, req *dto.UpdateMenuItemRequest) (*dto.MenuItemResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.MenuItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateMenuItemRequest) (*dto.MenuItemResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateMenuItemRequest) *dto.MenuItemResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.MenuItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateMenuItemRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMenuItemServiceInterface creates a new instance of MenuItemServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMenuItemServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MenuItemServiceInterface {
	mock := &MenuItemServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
