// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// ActivityLogServiceInterface is an autogenerated mock type for the ActivityLogServiceInterface type
type ActivityLogServiceInterface struct {
	mock.Mock
}

// GetActivityLogs provides a mock function with given fields: ctx, storeID, filter
func (_m *ActivityLogServiceInterface) GetActivityLogs(ctx context.Context, storeID string, filter dto.ActivityLogFilter) ([]dto.ActivityLogResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, storeID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityLogs")
	}

	var r0 []dto.ActivityLogResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ActivityLogFilter) ([]dto.ActivityLogResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, storeID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ActivityLogFilter) []dto.ActivityLogResponse); ok {
		r0 = rf(ctx, storeID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ActivityLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.ActivityLogFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, storeID, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, dto.ActivityLogFilter) error); ok {
		r2 = rf(ctx, storeID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LogActivity provides a mock function with given fields: ctx, userID, storeID, action, module, refID, metadata
func (_m *ActivityLogServiceInterface) LogActivity(ctx context.Context, userID string, storeID string, action domain.ActionType, module domain.ActivityModule, refID string, metadata interface{}) {
	_m.Called(ctx, userID, storeID, action, module, refID, metadata)
}

// NewActivityLogServiceInterface creates a new instance of ActivityLogServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityLogServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityLogServiceInterface {
	mock := &ActivityLogServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
