// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// BatchRepository is an autogenerated mock type for the BatchRepository type
type BatchRepository struct {
	mock.Mock
}

// CreateBatch provides a mock function with given fields: ctx, batch
func (_m *BatchRepository) CreateBatch(ctx context.Context, batch *domain.StockBatch) error {
	ret := _m.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StockBatch) error); ok {
		r0 = rf(ctx, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeductFIFO provides a mock function with given fields: ctx, productID, storeID, qty
func (_m *BatchRepository) DeductFIFO(ctx context.Context, productID string, storeID string, qty float64) error {
	ret := _m.Called(ctx, productID, storeID, qty)

	if len(ret) == 0 {
		panic("no return value specified for DeductFIFO")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) error); ok {
		r0 = rf(ctx, productID, storeID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBatchesByProduct provides a mock function with given fields: ctx, productID, storeID
func (_m *BatchRepository) GetBatchesByProduct(ctx context.Context, productID string, storeID string) ([]*domain.StockBatch, error) {
	ret := _m.Called(ctx, productID, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchesByProduct")
	}

	var r0 []*domain.StockBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*domain.StockBatch, error)); ok {
		return rf(ctx, productID, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*domain.StockBatch); ok {
		r0 = rf(ctx, productID, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StockBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, productID, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBatchesByStore provides a mock function with given fields: ctx, filter
func (_m *BatchRepository) GetBatchesByStore(ctx context.Context, filter dto.BatchListFilter) ([]*domain.StockBatch, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchesByStore")
	}

	var r0 []*domain.StockBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.BatchListFilter) ([]*domain.StockBatch, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.BatchListFilter) []*domain.StockBatch); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StockBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.BatchListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockSummary provides a mock function with given fields: ctx, storeID
func (_m *BatchRepository) GetStockSummary(ctx context.Context, storeID string) ([]*domain.BatchStockSummary, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetStockSummary")
	}

	var r0 []*domain.BatchStockSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.BatchStockSummary, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.BatchStockSummary); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.BatchStockSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBatchRepository creates a new instance of BatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchRepository {
	mock := &BatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
