// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type ExpenseRepository struct {
	mock.Mock
}

// BumpRecurringNextRun provides a mock function with given fields: ctx, id, nextRun
func (_m *ExpenseRepository) BumpRecurringNextRun(ctx context.Context, id string, nextRun string) error {
	ret := _m.Called(ctx, id, nextRun)

	if len(ret) == 0 {
		panic("no return value specified for BumpRecurringNextRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, nextRun)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCategory provides a mock function with given fields: ctx, c
func (_m *ExpenseRepository) CreateCategory(ctx context.Context, c *domain.ExpenseCategory) (*domain.ExpenseCategory, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *domain.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ExpenseCategory) (*domain.ExpenseCategory, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ExpenseCategory) *domain.ExpenseCategory); ok {
		r0 = rf(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.ExpenseCategory) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateExpense provides a mock function with given fields: ctx, e
func (_m *ExpenseRepository) CreateExpense(ctx context.Context, e *domain.Expense) (*domain.Expense, error) {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for CreateExpense")
	}

	var r0 *domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Expense) (*domain.Expense, error)); ok {
		return rf(ctx, e)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Expense) *domain.Expense); ok {
		r0 = rf(ctx, e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Expense) error); ok {
		r1 = rf(ctx, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRecurringExpense provides a mock function with given fields: ctx, e
func (_m *ExpenseRepository) CreateRecurringExpense(ctx context.Context, e *domain.RecurringExpense) (*domain.RecurringExpense, error) {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecurringExpense")
	}

	var r0 *domain.RecurringExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RecurringExpense) (*domain.RecurringExpense, error)); ok {
		return rf(ctx, e)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RecurringExpense) *domain.RecurringExpense); ok {
		r0 = rf(ctx, e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RecurringExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.RecurringExpense) error); ok {
		r1 = rf(ctx, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, storeID
func (_m *ExpenseRepository) Delete(ctx context.Context, id string, storeID string) error {
	ret := _m.Called(ctx, id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, storeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRecurring provides a mock function with given fields: ctx, id, storeID
func (_m *ExpenseRepository) DeleteRecurring(ctx context.Context, id string, storeID string) error {
	ret := _m.Called(ctx, id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecurring")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, storeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, f
func (_m *ExpenseRepository) FindAll(ctx context.Context, f dto.ExpenseListFilter) ([]*domain.Expense, int, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Expense
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExpenseListFilter) ([]*domain.Expense, int, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExpenseListFilter) []*domain.Expense); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ExpenseListFilter) int); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.ExpenseListFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAllRecurring provides a mock function with given fields: ctx, f
func (_m *ExpenseRepository) FindAllRecurring(ctx context.Context, f dto.ExpenseListFilter) ([]*domain.RecurringExpense, int, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for FindAllRecurring")
	}

	var r0 []*domain.RecurringExpense
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExpenseListFilter) ([]*domain.RecurringExpense, int, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExpenseListFilter) []*domain.RecurringExpense); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.RecurringExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ExpenseListFilter) int); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.ExpenseListFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id, storeID
func (_m *ExpenseRepository) GetByID(ctx context.Context, id string, storeID string) (*domain.Expense, error) {
	ret := _m.Called(ctx, id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Expense, error)); ok {
		return rf(ctx, id, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Expense); ok {
		r0 = rf(ctx, id, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByID provides a mock function with given fields: ctx, id
func (_m *ExpenseRepository) GetCategoryByID(ctx context.Context, id string) (*domain.ExpenseCategory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *domain.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ExpenseCategory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ExpenseCategory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDueRecurringExpenses provides a mock function with given fields: ctx
func (_m *ExpenseRepository) GetDueRecurringExpenses(ctx context.Context) ([]*domain.RecurringExpense, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDueRecurringExpenses")
	}

	var r0 []*domain.RecurringExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.RecurringExpense, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.RecurringExpense); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.RecurringExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecurringByID provides a mock function with given fields: ctx, id, storeID
func (_m *ExpenseRepository) GetRecurringByID(ctx context.Context, id string, storeID string) (*domain.RecurringExpense, error) {
	ret := _m.Called(ctx, id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecurringByID")
	}

	var r0 *domain.RecurringExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.RecurringExpense, error)); ok {
		return rf(ctx, id, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.RecurringExpense); ok {
		r0 = rf(ctx, id, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RecurringExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCategories provides a mock function with given fields: ctx, includeDeleted
func (_m *ExpenseRepository) ListCategories(ctx context.Context, includeDeleted bool) ([]*domain.ExpenseCategory, error) {
	ret := _m.Called(ctx, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []*domain.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]*domain.ExpenseCategory, error)); ok {
		return rf(ctx, includeDeleted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []*domain.ExpenseCategory); ok {
		r0 = rf(ctx, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDeleteCategory provides a mock function with given fields: ctx, id
func (_m *ExpenseRepository) SoftDeleteCategory(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, e
func (_m *ExpenseRepository) Update(ctx context.Context, e *domain.Expense) (*domain.Expense, error) {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Expense) (*domain.Expense, error)); ok {
		return rf(ctx, e)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Expense) *domain.Expense); ok {
		r0 = rf(ctx, e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Expense) error); ok {
		r1 = rf(ctx, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: ctx, id, name, desc, isActive
func (_m *ExpenseRepository) UpdateCategory(ctx context.Context, id string, name string, desc string, isActive bool) (*domain.ExpenseCategory, error) {
	ret := _m.Called(ctx, id, name, desc, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 *domain.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (*domain.ExpenseCategory, error)); ok {
		return rf(ctx, id, name, desc, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) *domain.ExpenseCategory); ok {
		r0 = rf(ctx, id, name, desc, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) error); ok {
		r1 = rf(ctx, id, name, desc, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePaymentStatus provides a mock function with given fields: ctx, id, storeID, status
func (_m *ExpenseRepository) UpdatePaymentStatus(ctx context.Context, id string, storeID string, status string) (*domain.Expense, error) {
	ret := _m.Called(ctx, id, storeID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 *domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.Expense, error)); ok {
		return rf(ctx, id, storeID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.Expense); ok {
		r0 = rf(ctx, id, storeID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, id, storeID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecurring provides a mock function with given fields: ctx, e
func (_m *ExpenseRepository) UpdateRecurring(ctx context.Context, e *domain.RecurringExpense) (*domain.RecurringExpense, error) {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecurring")
	}

	var r0 *domain.RecurringExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RecurringExpense) (*domain.RecurringExpense, error)); ok {
		return rf(ctx, e)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RecurringExpense) *domain.RecurringExpense); ok {
		r0 = rf(ctx, e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RecurringExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.RecurringExpense) error); ok {
		r1 = rf(ctx, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExpenseRepository creates a new instance of ExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseRepository {
	mock := &ExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
