// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// ExpenseServiceInterface is an autogenerated mock type for the ExpenseServiceInterface type
type ExpenseServiceInterface struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, req
func (_m *ExpenseServiceInterface) CreateCategory(ctx context.Context, req *dto.CreateExpenseCategoryRequest) (*dto.ExpenseCategoryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *dto.ExpenseCategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateExpenseCategoryRequest) (*dto.ExpenseCategoryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateExpenseCategoryRequest) *dto.ExpenseCategoryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseCategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateExpenseCategoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateExpense provides a mock function with given fields: ctx, storeID, userID, req
func (_m *ExpenseServiceInterface) CreateExpense(ctx context.Context, storeID string, userID string, req *dto.CreateExpenseRequest) (*dto.ExpenseResponse, error) {
	ret := _m.Called(ctx, storeID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateExpense")
	}

	var r0 *dto.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CreateExpenseRequest) (*dto.ExpenseResponse, error)); ok {
		return rf(ctx, storeID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CreateExpenseRequest) *dto.ExpenseResponse); ok {
		r0 = rf(ctx, storeID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.CreateExpenseRequest) error); ok {
		r1 = rf(ctx, storeID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRecurringExpense provides a mock function with given fields: ctx, storeID, userID, req
func (_m *ExpenseServiceInterface) CreateRecurringExpense(ctx context.Context, storeID string, userID string, req *dto.CreateRecurringExpenseRequest) (*dto.RecurringExpenseResponse, error) {
	ret := _m.Called(ctx, storeID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecurringExpense")
	}

	var r0 *dto.RecurringExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CreateRecurringExpenseRequest) (*dto.RecurringExpenseResponse, error)); ok {
		return rf(ctx, storeID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CreateRecurringExpenseRequest) *dto.RecurringExpenseResponse); ok {
		r0 = rf(ctx, storeID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RecurringExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.CreateRecurringExpenseRequest) error); ok {
		r1 = rf(ctx, storeID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteExpense provides a mock function with given fields: ctx, id, storeID
func (_m *ExpenseServiceInterface) DeleteExpense(ctx context.Context, id string, storeID string) error {
	ret := _m.Called(ctx, id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, storeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRecurringExpense provides a mock function with given fields: ctx, id, storeID
func (_m *ExpenseServiceInterface) DeleteRecurringExpense(ctx context.Context, id string, storeID string) error {
	ret := _m.Called(ctx, id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecurringExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, storeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListCategories provides a mock function with given fields: ctx, includeDeleted
func (_m *ExpenseServiceInterface) ListCategories(ctx context.Context, includeDeleted bool) ([]dto.ExpenseCategoryResponse, error) {
	ret := _m.Called(ctx, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []dto.ExpenseCategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]dto.ExpenseCategoryResponse, error)); ok {
		return rf(ctx, includeDeleted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []dto.ExpenseCategoryResponse); ok {
		r0 = rf(ctx, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ExpenseCategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListExpenses provides a mock function with given fields: ctx, filter
func (_m *ExpenseServiceInterface) ListExpenses(ctx context.Context, filter dto.ExpenseListFilter) ([]*dto.ExpenseResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListExpenses")
	}

	var r0 []*dto.ExpenseResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExpenseListFilter) ([]*dto.ExpenseResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExpenseListFilter) []*dto.ExpenseResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ExpenseListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.ExpenseListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListRecurringExpenses provides a mock function with given fields: ctx, filter
func (_m *ExpenseServiceInterface) ListRecurringExpenses(ctx context.Context, filter dto.ExpenseListFilter) ([]*dto.RecurringExpenseResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListRecurringExpenses")
	}

	var r0 []*dto.RecurringExpenseResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExpenseListFilter) ([]*dto.RecurringExpenseResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExpenseListFilter) []*dto.RecurringExpenseResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.RecurringExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ExpenseListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.ExpenseListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProcessDueRecurringExpenses provides a mock function with given fields: ctx
func (_m *ExpenseServiceInterface) ProcessDueRecurringExpenses(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProcessDueRecurringExpenses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDeleteCategory provides a mock function with given fields: ctx, id
func (_m *ExpenseServiceInterface) SoftDeleteCategory(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCategory provides a mock function with given fields: ctx, id, req
func (_m *ExpenseServiceInterface) UpdateCategory(ctx context.Context, id string, req *dto.UpdateExpenseCategoryRequest) (*dto.ExpenseCategoryResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 *dto.ExpenseCategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateExpenseCategoryRequest) (*dto.ExpenseCategoryResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateExpenseCategoryRequest) *dto.ExpenseCategoryResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseCategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateExpenseCategoryRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateExpense provides a mock function with given fields: ctx, id, storeID, req
func (_m *ExpenseServiceInterface) UpdateExpense(ctx context.Context, id string, storeID string, req *dto.UpdateExpenseRequest) (*dto.ExpenseResponse, error) {
	ret := _m.Called(ctx, id, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExpense")
	}

	var r0 *dto.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateExpenseRequest) (*dto.ExpenseResponse, error)); ok {
		return rf(ctx, id, storeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateExpenseRequest) *dto.ExpenseResponse); ok {
		r0 = rf(ctx, id, storeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.UpdateExpenseRequest) error); ok {
		r1 = rf(ctx, id, storeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePaymentStatus provides a mock function with given fields: ctx, id, storeID, req
func (_m *ExpenseServiceInterface) UpdatePaymentStatus(ctx context.Context, id string, storeID string, req *dto.UpdateExpenseStatusRequest) (*dto.ExpenseResponse, error) {
	ret := _m.Called(ctx, id, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 *dto.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateExpenseStatusRequest) (*dto.ExpenseResponse, error)); ok {
		return rf(ctx, id, storeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateExpenseStatusRequest) *dto.ExpenseResponse); ok {
		r0 = rf(ctx, id, storeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.UpdateExpenseStatusRequest) error); ok {
		r1 = rf(ctx, id, storeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecurringExpense provides a mock function with given fields: ctx, id, storeID, req
func (_m *ExpenseServiceInterface) UpdateRecurringExpense(ctx context.Context, id string, storeID string, req *dto.UpdateRecurringExpenseRequest) (*dto.RecurringExpenseResponse, error) {
	ret := _m.Called(ctx, id, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecurringExpense")
	}

	var r0 *dto.RecurringExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateRecurringExpenseRequest) (*dto.RecurringExpenseResponse, error)); ok {
		return rf(ctx, id, storeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateRecurringExpenseRequest) *dto.RecurringExpenseResponse); ok {
		r0 = rf(ctx, id, storeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RecurringExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dto.UpdateRecurringExpenseRequest) error); ok {
		r1 = rf(ctx, id, storeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExpenseServiceInterface creates a new instance of ExpenseServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseServiceInterface {
	mock := &ExpenseServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
