// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MenuItemRepository is an autogenerated mock type for the MenuItemRepository type
type MenuItemRepository struct {
	mock.Mock
}

// FindAllByStore provides a mock function with given fields: ctx, storeID
func (_m *MenuItemRepository) FindAllByStore(ctx context.Context, storeID string) ([]*domain.MenuItem, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByStore")
	}

	var r0 []*domain.MenuItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.MenuItem, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.MenuItem); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MenuItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MenuItemRepository) FindByID(ctx context.Context, id string) (*domain.MenuItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.MenuItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.MenuItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.MenuItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MenuItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMenuItemRepository creates a new instance of MenuItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMenuItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MenuItemRepository {
	mock := &MenuItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
