// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// POPaymentRepository is an autogenerated mock type for the POPaymentRepository type
type POPaymentRepository struct {
	mock.Mock
}

// AggregateByPO provides a mock function with given fields: ctx, poID, totalAmount
func (_m *POPaymentRepository) AggregateByPO(ctx context.Context, poID string, totalAmount float64) (float64, string, error) {
	ret := _m.Called(ctx, poID, totalAmount)

	if len(ret) == 0 {
		panic("no return value specified for AggregateByPO")
	}

	var r0 float64
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) (float64, string, error)); ok {
		return rf(ctx, poID, totalAmount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) float64); ok {
		r0 = rf(ctx, poID, totalAmount)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64) string); ok {
		r1 = rf(ctx, poID, totalAmount)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, float64) error); ok {
		r2 = rf(ctx, poID, totalAmount)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Create provides a mock function with given fields: ctx, p
func (_m *POPaymentRepository) Create(ctx context.Context, p domain.POPayment) (*domain.POPayment, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.POPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.POPayment) (*domain.POPayment, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.POPayment) *domain.POPayment); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.POPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.POPayment) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPO provides a mock function with given fields: ctx, poID
func (_m *POPaymentRepository) FindByPO(ctx context.Context, poID string) ([]*domain.POPayment, error) {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPO")
	}

	var r0 []*domain.POPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.POPayment, error)); ok {
		return rf(ctx, poID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.POPayment); ok {
		r0 = rf(ctx, poID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.POPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayableSummary provides a mock function with given fields: ctx, storeID
func (_m *POPaymentRepository) PayableSummary(ctx context.Context, storeID string) (*dto.PayableSummary, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for PayableSummary")
	}

	var r0 *dto.PayableSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.PayableSummary, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.PayableSummary); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PayableSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PopulatePOPayments provides a mock function with given fields: ctx, pos
func (_m *POPaymentRepository) PopulatePOPayments(ctx context.Context, pos []*domain.PurchaseOrder) {
	_m.Called(ctx, pos)
}

// NewPOPaymentRepository creates a new instance of POPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPOPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *POPaymentRepository {
	mock := &POPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
