// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// PriceHistoryRepository is an autogenerated mock type for the PriceHistoryRepository type
type PriceHistoryRepository struct {
	mock.Mock
}

// FindByProduct provides a mock function with given fields: ctx, productID, f
func (_m *PriceHistoryRepository) FindByProduct(ctx context.Context, productID string, f dto.PriceHistoryFilter) ([]*domain.PriceHistory, int, error) {
	ret := _m.Called(ctx, productID, f)

	if len(ret) == 0 {
		panic("no return value specified for FindByProduct")
	}

	var r0 []*domain.PriceHistory
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.PriceHistoryFilter) ([]*domain.PriceHistory, int, error)); ok {
		return rf(ctx, productID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.PriceHistoryFilter) []*domain.PriceHistory); ok {
		r0 = rf(ctx, productID, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.PriceHistoryFilter) int); ok {
		r1 = rf(ctx, productID, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, dto.PriceHistoryFilter) error); ok {
		r2 = rf(ctx, productID, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByStore provides a mock function with given fields: ctx, storeID, f
func (_m *PriceHistoryRepository) FindByStore(ctx context.Context, storeID string, f dto.PriceHistoryFilter) ([]*domain.PriceHistory, int, error) {
	ret := _m.Called(ctx, storeID, f)

	if len(ret) == 0 {
		panic("no return value specified for FindByStore")
	}

	var r0 []*domain.PriceHistory
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.PriceHistoryFilter) ([]*domain.PriceHistory, int, error)); ok {
		return rf(ctx, storeID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.PriceHistoryFilter) []*domain.PriceHistory); ok {
		r0 = rf(ctx, storeID, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.PriceHistoryFilter) int); ok {
		r1 = rf(ctx, storeID, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, dto.PriceHistoryFilter) error); ok {
		r2 = rf(ctx, storeID, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Record provides a mock function with given fields: ctx, h
func (_m *PriceHistoryRepository) Record(ctx context.Context, h domain.PriceHistory) error {
	ret := _m.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PriceHistory) error); ok {
		r0 = rf(ctx, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPriceHistoryRepository creates a new instance of PriceHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceHistoryRepository {
	mock := &PriceHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
