// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// ProductServiceInterface is an autogenerated mock type for the ProductServiceInterface type
type ProductServiceInterface struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, storeID, req
func (_m *ProductServiceInterface) CreateCategory(ctx context.Context, storeID string, req *dto.CreateCategoryRequest) (*dto.CategoryResponse, error) {
	ret := _m.Called(ctx, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *dto.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateCategoryRequest) (*dto.CategoryResponse, error)); ok {
		return rf(ctx, storeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateCategoryRequest) *dto.CategoryResponse); ok {
		r0 = rf(ctx, storeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.CreateCategoryRequest) error); ok {
		r1 = rf(ctx, storeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProduct provides a mock function with given fields: ctx, storeID, req, createdByID
func (_m *ProductServiceInterface) CreateProduct(ctx context.Context, storeID string, req *dto.CreateProductRequest, createdByID string) (*dto.ProductResponse, error) {
	ret := _m.Called(ctx, storeID, req, createdByID)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *dto.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateProductRequest, string) (*dto.ProductResponse, error)); ok {
		return rf(ctx, storeID, req, createdByID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.CreateProductRequest, string) *dto.ProductResponse); ok {
		r0 = rf(ctx, storeID, req, createdByID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.CreateProductRequest, string) error); ok {
		r1 = rf(ctx, storeID, req, createdByID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCategory provides a mock function with given fields: ctx, id
func (_m *ProductServiceInterface) DeleteCategory(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *ProductServiceInterface) DeleteProduct(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProduct provides a mock function with given fields: ctx, id
func (_m *ProductServiceInterface) GetProduct(ctx context.Context, id string) (*dto.ProductResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *dto.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.ProductResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.ProductResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByBarcode provides a mock function with given fields: ctx, storeID, barcode
func (_m *ProductServiceInterface) GetProductByBarcode(ctx context.Context, storeID string, barcode string) (*dto.ProductResponse, error) {
	ret := _m.Called(ctx, storeID, barcode)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByBarcode")
	}

	var r0 *dto.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.ProductResponse, error)); ok {
		return rf(ctx, storeID, barcode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.ProductResponse); ok {
		r0 = rf(ctx, storeID, barcode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, storeID, barcode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCategories provides a mock function with given fields: ctx, storeID
func (_m *ProductServiceInterface) ListCategories(ctx context.Context, storeID string) ([]*dto.CategoryResponse, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []*dto.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.CategoryResponse, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.CategoryResponse); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProducts provides a mock function with given fields: ctx, filter
func (_m *ProductServiceInterface) ListProducts(ctx context.Context, filter dto.ProductListFilter) ([]*dto.ProductResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []*dto.ProductResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ProductListFilter) ([]*dto.ProductResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ProductListFilter) []*dto.ProductResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ProductListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.ProductListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateCategory provides a mock function with given fields: ctx, id, req
func (_m *ProductServiceInterface) UpdateCategory(ctx context.Context, id string, req *dto.UpdateCategoryRequest) (*dto.CategoryResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 *dto.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateCategoryRequest) (*dto.CategoryResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateCategoryRequest) *dto.CategoryResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateCategoryRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, id, req, changedBy
func (_m *ProductServiceInterface) UpdateProduct(ctx context.Context, id string, req *dto.UpdateProductRequest, changedBy string) (*dto.ProductResponse, error) {
	ret := _m.Called(ctx, id, req, changedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *dto.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateProductRequest, string) (*dto.ProductResponse, error)); ok {
		return rf(ctx, id, req, changedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateProductRequest, string) *dto.ProductResponse); ok {
		r0 = rf(ctx, id, req, changedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateProductRequest, string) error); ok {
		r1 = rf(ctx, id, req, changedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductServiceInterface creates a new instance of ProductServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductServiceInterface {
	mock := &ProductServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
