// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// PurchaseOrderRepository is an autogenerated mock type for the PurchaseOrderRepository type
type PurchaseOrderRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, poID
func (_m *PurchaseOrderRepository) Cancel(ctx context.Context, poID string) error {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, poID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, po, items
func (_m *PurchaseOrderRepository) Create(ctx context.Context, po *domain.PurchaseOrder, items []domain.POItem) (*domain.PurchaseOrder, error) {
	ret := _m.Called(ctx, po, items)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.PurchaseOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PurchaseOrder, []domain.POItem) (*domain.PurchaseOrder, error)); ok {
		return rf(ctx, po, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PurchaseOrder, []domain.POItem) *domain.PurchaseOrder); ok {
		r0 = rf(ctx, po, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PurchaseOrder, []domain.POItem) error); ok {
		r1 = rf(ctx, po, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *PurchaseOrderRepository) FindAll(ctx context.Context, filter dto.POListFilter) ([]*domain.PurchaseOrder, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.PurchaseOrder
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.POListFilter) ([]*domain.PurchaseOrder, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.POListFilter) []*domain.PurchaseOrder); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.POListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.POListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PurchaseOrderRepository) FindByID(ctx context.Context, id string) (*domain.PurchaseOrder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.PurchaseOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PurchaseOrder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PurchaseOrder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Receive provides a mock function with given fields: ctx, poID, userID
func (_m *PurchaseOrderRepository) Receive(ctx context.Context, poID string, userID string) error {
	ret := _m.Called(ctx, poID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, poID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Submit provides a mock function with given fields: ctx, poID, userID
func (_m *PurchaseOrderRepository) Submit(ctx context.Context, poID string, userID string) error {
	ret := _m.Called(ctx, poID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, poID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, po, items
func (_m *PurchaseOrderRepository) Update(ctx context.Context, po *domain.PurchaseOrder, items []domain.POItem) (*domain.PurchaseOrder, error) {
	ret := _m.Called(ctx, po, items)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.PurchaseOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PurchaseOrder, []domain.POItem) (*domain.PurchaseOrder, error)); ok {
		return rf(ctx, po, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PurchaseOrder, []domain.POItem) *domain.PurchaseOrder); ok {
		r0 = rf(ctx, po, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PurchaseOrder, []domain.POItem) error); ok {
		r1 = rf(ctx, po, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPurchaseOrderRepository creates a new instance of PurchaseOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPurchaseOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PurchaseOrderRepository {
	mock := &PurchaseOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
