// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

// CashFlowDetail provides a mock function with given fields: ctx, storeID, from, to
func (_m *ReportRepository) CashFlowDetail(ctx context.Context, storeID string, from time.Time, to time.Time) ([]dto.CashFlowDetailEntry, error) {
	ret := _m.Called(ctx, storeID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CashFlowDetail")
	}

	var r0 []dto.CashFlowDetailEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]dto.CashFlowDetailEntry, error)); ok {
		return rf(ctx, storeID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []dto.CashFlowDetailEntry); ok {
		r0 = rf(ctx, storeID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CashFlowDetailEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, storeID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashFlowSummary provides a mock function with given fields: ctx, storeID, from, to
func (_m *ReportRepository) CashFlowSummary(ctx context.Context, storeID string, from time.Time, to time.Time) ([]dto.CashFlowDayRow, error) {
	ret := _m.Called(ctx, storeID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CashFlowSummary")
	}

	var r0 []dto.CashFlowDayRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]dto.CashFlowDayRow, error)); ok {
		return rf(ctx, storeID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []dto.CashFlowDayRow); ok {
		r0 = rf(ctx, storeID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CashFlowDayRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, storeID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfitSummary provides a mock function with given fields: ctx, storeID, from, to, groupBy
func (_m *ReportRepository) ProfitSummary(ctx context.Context, storeID string, from time.Time, to time.Time, groupBy string) ([]dto.ProfitPeriodRow, error) {
	ret := _m.Called(ctx, storeID, from, to, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for ProfitSummary")
	}

	var r0 []dto.ProfitPeriodRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, string) ([]dto.ProfitPeriodRow, error)); ok {
		return rf(ctx, storeID, from, to, groupBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, string) []dto.ProfitPeriodRow); ok {
		r0 = rf(ctx, storeID, from, to, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProfitPeriodRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, string) error); ok {
		r1 = rf(ctx, storeID, from, to, groupBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SalesByCashier provides a mock function with given fields: ctx, storeID, from, to
func (_m *ReportRepository) SalesByCashier(ctx context.Context, storeID string, from time.Time, to time.Time) ([]dto.SalesByCashierRow, error) {
	ret := _m.Called(ctx, storeID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SalesByCashier")
	}

	var r0 []dto.SalesByCashierRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]dto.SalesByCashierRow, error)); ok {
		return rf(ctx, storeID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []dto.SalesByCashierRow); ok {
		r0 = rf(ctx, storeID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SalesByCashierRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, storeID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SalesByProduct provides a mock function with given fields: ctx, storeID, from, to
func (_m *ReportRepository) SalesByProduct(ctx context.Context, storeID string, from time.Time, to time.Time) ([]dto.SalesByProductRow, error) {
	ret := _m.Called(ctx, storeID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SalesByProduct")
	}

	var r0 []dto.SalesByProductRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]dto.SalesByProductRow, error)); ok {
		return rf(ctx, storeID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []dto.SalesByProductRow); ok {
		r0 = rf(ctx, storeID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SalesByProductRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, storeID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SalesSummary provides a mock function with given fields: ctx, storeID, from, to
func (_m *ReportRepository) SalesSummary(ctx context.Context, storeID string, from time.Time, to time.Time) ([]dto.SalesSummaryRow, error) {
	ret := _m.Called(ctx, storeID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SalesSummary")
	}

	var r0 []dto.SalesSummaryRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]dto.SalesSummaryRow, error)); ok {
		return rf(ctx, storeID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []dto.SalesSummaryRow); ok {
		r0 = rf(ctx, storeID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SalesSummaryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, storeID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StockValuation provides a mock function with given fields: ctx, storeID
func (_m *ReportRepository) StockValuation(ctx context.Context, storeID string) ([]dto.StockValuationRow, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for StockValuation")
	}

	var r0 []dto.StockValuationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.StockValuationRow, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.StockValuationRow); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.StockValuationRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
