// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// StockRepository is an autogenerated mock type for the StockRepository type
type StockRepository struct {
	mock.Mock
}

// Adjust provides a mock function with given fields: ctx, input
func (_m *StockRepository) Adjust(ctx context.Context, input domain.AdjustInput) (*domain.StockLevel, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Adjust")
	}

	var r0 *domain.StockLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AdjustInput) (*domain.StockLevel, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AdjustInput) *domain.StockLevel); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StockLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AdjustInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeductStock provides a mock function with given fields: ctx, productID, storeID, qty, refID, cashierID
func (_m *StockRepository) DeductStock(ctx context.Context, productID string, storeID string, qty float64, refID string, cashierID string) error {
	ret := _m.Called(ctx, productID, storeID, qty, refID, cashierID)

	if len(ret) == 0 {
		panic("no return value specified for DeductStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, string, string) error); ok {
		r0 = rf(ctx, productID, storeID, qty, refID, cashierID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindLevelByProduct provides a mock function with given fields: ctx, productID, storeID
func (_m *StockRepository) FindLevelByProduct(ctx context.Context, productID string, storeID string) (*domain.StockLevel, error) {
	ret := _m.Called(ctx, productID, storeID)

	if len(ret) == 0 {
		panic("no return value specified for FindLevelByProduct")
	}

	var r0 *domain.StockLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.StockLevel, error)); ok {
		return rf(ctx, productID, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.StockLevel); ok {
		r0 = rf(ctx, productID, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StockLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, productID, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLevelsByStore provides a mock function with given fields: ctx, storeID, lowStockOnly
func (_m *StockRepository) FindLevelsByStore(ctx context.Context, storeID string, lowStockOnly bool) ([]*domain.StockLevel, error) {
	ret := _m.Called(ctx, storeID, lowStockOnly)

	if len(ret) == 0 {
		panic("no return value specified for FindLevelsByStore")
	}

	var r0 []*domain.StockLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) ([]*domain.StockLevel, error)); ok {
		return rf(ctx, storeID, lowStockOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) []*domain.StockLevel); ok {
		r0 = rf(ctx, storeID, lowStockOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StockLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, storeID, lowStockOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMovements provides a mock function with given fields: ctx, filter
func (_m *StockRepository) FindMovements(ctx context.Context, filter dto.StockMovementFilter) ([]*domain.StockMovement, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindMovements")
	}

	var r0 []*domain.StockMovement
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.StockMovementFilter) ([]*domain.StockMovement, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.StockMovementFilter) []*domain.StockMovement); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StockMovement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.StockMovementFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.StockMovementFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetModifiedSince provides a mock function with given fields: ctx, storeID, since
func (_m *StockRepository) GetModifiedSince(ctx context.Context, storeID string, since time.Time) ([]*domain.StockLevel, error) {
	ret := _m.Called(ctx, storeID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetModifiedSince")
	}

	var r0 []*domain.StockLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.StockLevel, error)); ok {
		return rf(ctx, storeID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.StockLevel); ok {
		r0 = rf(ctx, storeID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StockLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, storeID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetMinQuantity provides a mock function with given fields: ctx, productID, storeID, min
func (_m *StockRepository) SetMinQuantity(ctx context.Context, productID string, storeID string, min float64) error {
	ret := _m.Called(ctx, productID, storeID, min)

	if len(ret) == 0 {
		panic("no return value specified for SetMinQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) error); ok {
		r0 = rf(ctx, productID, storeID, min)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStockRepository creates a new instance of StockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockRepository {
	mock := &StockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
