// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// StockServiceInterface is an autogenerated mock type for the StockServiceInterface type
type StockServiceInterface struct {
	mock.Mock
}

// AdjustStock provides a mock function with given fields: ctx, storeID, req, userID
func (_m *StockServiceInterface) AdjustStock(ctx context.Context, storeID string, req *dto.AdjustStockRequest, userID string) (*dto.StockLevelResponse, error) {
	ret := _m.Called(ctx, storeID, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for AdjustStock")
	}

	var r0 *dto.StockLevelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.AdjustStockRequest, string) (*dto.StockLevelResponse, error)); ok {
		return rf(ctx, storeID, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.AdjustStockRequest, string) *dto.StockLevelResponse); ok {
		r0 = rf(ctx, storeID, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StockLevelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.AdjustStockRequest, string) error); ok {
		r1 = rf(ctx, storeID, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMovements provides a mock function with given fields: ctx, filter
func (_m *StockServiceInterface) GetMovements(ctx context.Context, filter dto.StockMovementFilter) ([]*dto.StockMovementResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetMovements")
	}

	var r0 []*dto.StockMovementResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.StockMovementFilter) ([]*dto.StockMovementResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.StockMovementFilter) []*dto.StockMovementResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.StockMovementResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.StockMovementFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.StockMovementFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetProductStock provides a mock function with given fields: ctx, productID, storeID
func (_m *StockServiceInterface) GetProductStock(ctx context.Context, productID string, storeID string) (*dto.StockLevelResponse, error) {
	ret := _m.Called(ctx, productID, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductStock")
	}

	var r0 *dto.StockLevelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.StockLevelResponse, error)); ok {
		return rf(ctx, productID, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.StockLevelResponse); ok {
		r0 = rf(ctx, productID, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StockLevelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, productID, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockLevels provides a mock function with given fields: ctx, storeID, lowStockOnly
func (_m *StockServiceInterface) GetStockLevels(ctx context.Context, storeID string, lowStockOnly bool) ([]*dto.StockLevelResponse, error) {
	ret := _m.Called(ctx, storeID, lowStockOnly)

	if len(ret) == 0 {
		panic("no return value specified for GetStockLevels")
	}

	var r0 []*dto.StockLevelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) ([]*dto.StockLevelResponse, error)); ok {
		return rf(ctx, storeID, lowStockOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) []*dto.StockLevelResponse); ok {
		r0 = rf(ctx, storeID, lowStockOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.StockLevelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, storeID, lowStockOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetMinStock provides a mock function with given fields: ctx, storeID, req
func (_m *StockServiceInterface) SetMinStock(ctx context.Context, storeID string, req *dto.SetMinStockRequest) error {
	ret := _m.Called(ctx, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for SetMinStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.SetMinStockRequest) error); ok {
		r0 = rf(ctx, storeID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStockServiceInterface creates a new instance of StockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockServiceInterface {
	mock := &StockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
