// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// StoreServiceInterface is an autogenerated mock type for the StoreServiceInterface type
type StoreServiceInterface struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, storeID, req
func (_m *StoreServiceInterface) AddMember(ctx context.Context, storeID string, req *dto.AddMemberRequest) error {
	ret := _m.Called(ctx, storeID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.AddMemberRequest) error); ok {
		r0 = rf(ctx, storeID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateStore provides a mock function with given fields: ctx, req
func (_m *StoreServiceInterface) CreateStore(ctx context.Context, req *dto.CreateStoreRequest) (*dto.StoreResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateStore")
	}

	var r0 *dto.StoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateStoreRequest) (*dto.StoreResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateStoreRequest) *dto.StoreResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateStoreRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteStore provides a mock function with given fields: ctx, id
func (_m *StoreServiceInterface) DeleteStore(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStore provides a mock function with given fields: ctx, id
func (_m *StoreServiceInterface) GetStore(ctx context.Context, id string) (*dto.StoreResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStore")
	}

	var r0 *dto.StoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.StoreResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.StoreResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMembers provides a mock function with given fields: ctx, storeID
func (_m *StoreServiceInterface) ListMembers(ctx context.Context, storeID string) ([]*dto.MemberResponse, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []*dto.MemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.MemberResponse, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.MemberResponse); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.MemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListStores provides a mock function with given fields: ctx, f
func (_m *StoreServiceInterface) ListStores(ctx context.Context, f dto.StoreListFilter) ([]*dto.StoreResponse, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for ListStores")
	}

	var r0 []*dto.StoreResponse
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.StoreListFilter) ([]*dto.StoreResponse, dto.PaginationMeta, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.StoreListFilter) []*dto.StoreResponse); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.StoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.StoreListFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.StoreListFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RemoveMember provides a mock function with given fields: ctx, storeID, userID
func (_m *StoreServiceInterface) RemoveMember(ctx context.Context, storeID string, userID string) error {
	ret := _m.Called(ctx, storeID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, storeID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMemberRole provides a mock function with given fields: ctx, storeID, userID, req
func (_m *StoreServiceInterface) UpdateMemberRole(ctx context.Context, storeID string, userID string, req *dto.UpdateMemberRoleRequest) error {
	ret := _m.Called(ctx, storeID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateMemberRoleRequest) error); ok {
		r0 = rf(ctx, storeID, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStore provides a mock function with given fields: ctx, id, req
func (_m *StoreServiceInterface) UpdateStore(ctx context.Context, id string, req *dto.UpdateStoreRequest) (*dto.StoreResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStore")
	}

	var r0 *dto.StoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateStoreRequest) (*dto.StoreResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateStoreRequest) *dto.StoreResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateStoreRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStoreServiceInterface creates a new instance of StoreServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreServiceInterface {
	mock := &StoreServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
