// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SyncServiceInterface is an autogenerated mock type for the SyncServiceInterface type
type SyncServiceInterface struct {
	mock.Mock
}

// Pull provides a mock function with given fields: ctx, storeID, since
func (_m *SyncServiceInterface) Pull(ctx context.Context, storeID string, since time.Time) (*dto.SyncPullOutput, error) {
	ret := _m.Called(ctx, storeID, since)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 *dto.SyncPullOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*dto.SyncPullOutput, error)); ok {
		return rf(ctx, storeID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *dto.SyncPullOutput); ok {
		r0 = rf(ctx, storeID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SyncPullOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, storeID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSyncServiceInterface creates a new instance of SyncServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncServiceInterface {
	mock := &SyncServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
