// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/moedahpos/backend/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// TerminServiceInterface is an autogenerated mock type for the TerminServiceInterface type
type TerminServiceInterface struct {
	mock.Mock
}

// CalculatePODebt provides a mock function with given fields: ctx, poID
func (_m *TerminServiceInterface) CalculatePODebt(ctx context.Context, poID string) (*dto.PODebtSummaryResponse, error) {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for CalculatePODebt")
	}

	var r0 *dto.PODebtSummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.PODebtSummaryResponse, error)); ok {
		return rf(ctx, poID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.PODebtSummaryResponse); ok {
		r0 = rf(ctx, poID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PODebtSummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTerminSchedule provides a mock function with given fields: ctx, poID, req
func (_m *TerminServiceInterface) CreateTerminSchedule(ctx context.Context, poID string, req dto.CreateTerminScheduleRequest) ([]dto.TerminResponse, error) {
	ret := _m.Called(ctx, poID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTerminSchedule")
	}

	var r0 []dto.TerminResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.CreateTerminScheduleRequest) ([]dto.TerminResponse, error)); ok {
		return rf(ctx, poID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.CreateTerminScheduleRequest) []dto.TerminResponse); ok {
		r0 = rf(ctx, poID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.TerminResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.CreateTerminScheduleRequest) error); ok {
		r1 = rf(ctx, poID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateDocumentData provides a mock function with given fields: ctx, poID, docType
func (_m *TerminServiceInterface) GenerateDocumentData(ctx context.Context, poID string, docType string) (*dto.PODocumentData, error) {
	ret := _m.Called(ctx, poID, docType)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDocumentData")
	}

	var r0 *dto.PODocumentData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.PODocumentData, error)); ok {
		return rf(ctx, poID, docType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.PODocumentData); ok {
		r0 = rf(ctx, poID, docType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PODocumentData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, poID, docType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerminSchedule provides a mock function with given fields: ctx, poID
func (_m *TerminServiceInterface) GetTerminSchedule(ctx context.Context, poID string) ([]dto.TerminResponse, error) {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for GetTerminSchedule")
	}

	var r0 []dto.TerminResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.TerminResponse, error)); ok {
		return rf(ctx, poID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.TerminResponse); ok {
		r0 = rf(ctx, poID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.TerminResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordPayment provides a mock function with given fields: ctx, terminID, userID, req
func (_m *TerminServiceInterface) RecordPayment(ctx context.Context, terminID string, userID string, req dto.RecordPaymentRequest) (*dto.PaymentRecordResponse, error) {
	ret := _m.Called(ctx, terminID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordPayment")
	}

	var r0 *dto.PaymentRecordResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.RecordPaymentRequest) (*dto.PaymentRecordResponse, error)); ok {
		return rf(ctx, terminID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.RecordPaymentRequest) *dto.PaymentRecordResponse); ok {
		r0 = rf(ctx, terminID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PaymentRecordResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.RecordPaymentRequest) error); ok {
		r1 = rf(ctx, terminID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTerminServiceInterface creates a new instance of TerminServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerminServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerminServiceInterface {
	mock := &TerminServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
