// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, input
func (_m *TransactionRepository) Create(ctx context.Context, input domain.CreateTransactionInput) (*domain.Transaction, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTransactionInput) (*domain.Transaction, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTransactionInput) *domain.Transaction); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateTransactionInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *TransactionRepository) FindAll(ctx context.Context, filter dto.TransactionListFilter) ([]*domain.Transaction, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Transaction
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.TransactionListFilter) ([]*domain.Transaction, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.TransactionListFilter) []*domain.Transaction); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.TransactionListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.TransactionListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *TransactionRepository) FindByID(ctx context.Context, id string) (*domain.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDraftByTable provides a mock function with given fields: ctx, storeID, tableID
func (_m *TransactionRepository) GetDraftByTable(ctx context.Context, storeID string, tableID string) (*domain.Transaction, error) {
	ret := _m.Called(ctx, storeID, tableID)

	if len(ret) == 0 {
		panic("no return value specified for GetDraftByTable")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Transaction, error)); ok {
		return rf(ctx, storeID, tableID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Transaction); ok {
		r0 = rf(ctx, storeID, tableID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, storeID, tableID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKDSTickets provides a mock function with given fields: ctx, storeID
func (_m *TransactionRepository) GetKDSTickets(ctx context.Context, storeID string) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetKDSTickets")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Transaction, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Transaction); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayDraft provides a mock function with given fields: ctx, input, storeID, cashierID
func (_m *TransactionRepository) PayDraft(ctx context.Context, input domain.PayDraftInput, storeID string, cashierID string) (*domain.Transaction, error) {
	ret := _m.Called(ctx, input, storeID, cashierID)

	if len(ret) == 0 {
		panic("no return value specified for PayDraft")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PayDraftInput, string, string) (*domain.Transaction, error)); ok {
		return rf(ctx, input, storeID, cashierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PayDraftInput, string, string) *domain.Transaction); ok {
		r0 = rf(ctx, input, storeID, cashierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PayDraftInput, string, string) error); ok {
		r1 = rf(ctx, input, storeID, cashierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDraftItems provides a mock function with given fields: ctx, txnID, items, subtotal, discountAmt, taxAmt, total, customerName, notes
func (_m *TransactionRepository) UpdateDraftItems(ctx context.Context, txnID string, items []domain.CreateTransactionItemInput, subtotal float64, discountAmt float64, taxAmt float64, total float64, customerName string, notes string) (*domain.Transaction, error) {
	ret := _m.Called(ctx, txnID, items, subtotal, discountAmt, taxAmt, total, customerName, notes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDraftItems")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.CreateTransactionItemInput, float64, float64, float64, float64, string, string) (*domain.Transaction, error)); ok {
		return rf(ctx, txnID, items, subtotal, discountAmt, taxAmt, total, customerName, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.CreateTransactionItemInput, float64, float64, float64, float64, string, string) *domain.Transaction); ok {
		r0 = rf(ctx, txnID, items, subtotal, discountAmt, taxAmt, total, customerName, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []domain.CreateTransactionItemInput, float64, float64, float64, float64, string, string) error); ok {
		r1 = rf(ctx, txnID, items, subtotal, discountAmt, taxAmt, total, customerName, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKDSItemStatus provides a mock function with given fields: ctx, itemID, status
func (_m *TransactionRepository) UpdateKDSItemStatus(ctx context.Context, itemID string, status string) error {
	ret := _m.Called(ctx, itemID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKDSItemStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, itemID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Void provides a mock function with given fields: ctx, txnID, userID
func (_m *TransactionRepository) Void(ctx context.Context, txnID string, userID string) error {
	ret := _m.Called(ctx, txnID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Void")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, txnID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
