// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// ActivityLogRepository is an autogenerated mock type for the ActivityLogRepository type
type ActivityLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, log
func (_m *ActivityLogRepository) Create(ctx context.Context, log *domain.ActivityLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ActivityLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, storeID, filter
func (_m *ActivityLogRepository) FindAll(ctx context.Context, storeID string, filter dto.ActivityLogFilter) ([]*domain.ActivityLog, int, error) {
	ret := _m.Called(ctx, storeID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.ActivityLog
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ActivityLogFilter) ([]*domain.ActivityLog, int, error)); ok {
		return rf(ctx, storeID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ActivityLogFilter) []*domain.ActivityLog); ok {
		r0 = rf(ctx, storeID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ActivityLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.ActivityLogFilter) int); ok {
		r1 = rf(ctx, storeID, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, dto.ActivityLogFilter) error); ok {
		r2 = rf(ctx, storeID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewActivityLogRepository creates a new instance of ActivityLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityLogRepository {
	mock := &ActivityLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
