// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, cat
func (_m *CategoryRepository) Create(ctx context.Context, cat *domain.Category) (*domain.Category, error) {
	ret := _m.Called(ctx, cat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) (*domain.Category, error)); ok {
		return rf(ctx, cat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) *domain.Category); ok {
		r0 = rf(ctx, cat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Category) error); ok {
		r1 = rf(ctx, cat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByStore provides a mock function with given fields: ctx, storeID
func (_m *CategoryRepository) FindAllByStore(ctx context.Context, storeID string) ([]*domain.Category, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByStore")
	}

	var r0 []*domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Category, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Category); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *CategoryRepository) FindByID(ctx context.Context, id string) (*domain.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *CategoryRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, cat
func (_m *CategoryRepository) Update(ctx context.Context, cat *domain.Category) (*domain.Category, error) {
	ret := _m.Called(ctx, cat)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) (*domain.Category, error)); ok {
		return rf(ctx, cat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) *domain.Category); ok {
		r0 = rf(ctx, cat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Category) error); ok {
		r1 = rf(ctx, cat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
