// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, c
func (_m *CustomerRepository) Create(ctx context.Context, c *domain.Customer) (*domain.Customer, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Customer) (*domain.Customer, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Customer) *domain.Customer); ok {
		r0 = rf(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Customer) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, f
func (_m *CustomerRepository) FindAll(ctx context.Context, f dto.CustomerListFilter) ([]*domain.Customer, int, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Customer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CustomerListFilter) ([]*domain.Customer, int, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CustomerListFilter) []*domain.Customer); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CustomerListFilter) int); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.CustomerListFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *CustomerRepository) FindByID(ctx context.Context, id string) (*domain.Customer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Customer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Customer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByPhone provides a mock function with given fields: ctx, storeID, phone
func (_m *CustomerRepository) SearchByPhone(ctx context.Context, storeID string, phone string) ([]*domain.Customer, error) {
	ret := _m.Called(ctx, storeID, phone)

	if len(ret) == 0 {
		panic("no return value specified for SearchByPhone")
	}

	var r0 []*domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*domain.Customer, error)); ok {
		return rf(ctx, storeID, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*domain.Customer); ok {
		r0 = rf(ctx, storeID, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, storeID, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetModifiedSince provides a mock function with given fields: ctx, storeID, since
func (_m *CustomerRepository) GetModifiedSince(ctx context.Context, storeID string, since time.Time) ([]*domain.Customer, error) {
	ret := _m.Called(ctx, storeID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetModifiedSince")
	}

	var r0 []*domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.Customer, error)); ok {
		return rf(ctx, storeID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.Customer); ok {
		r0 = rf(ctx, storeID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, storeID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *CustomerRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, c
func (_m *CustomerRepository) Update(ctx context.Context, c *domain.Customer) (*domain.Customer, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Customer) (*domain.Customer, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Customer) *domain.Customer); ok {
		r0 = rf(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Customer) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerRepository creates a new instance of CustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerRepository {
	mock := &CustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
