// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// IncomeRepository is an autogenerated mock type for the IncomeRepository type
type IncomeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, inc
func (_m *IncomeRepository) Create(ctx context.Context, inc *domain.Income) (*domain.Income, error) {
	ret := _m.Called(ctx, inc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Income) (*domain.Income, error)); ok {
		return rf(ctx, inc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Income) *domain.Income); ok {
		r0 = rf(ctx, inc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Income) error); ok {
		r1 = rf(ctx, inc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCategory provides a mock function with given fields: ctx, cat
func (_m *IncomeRepository) CreateCategory(ctx context.Context, cat *domain.IncomeCategory) (*domain.IncomeCategory, error) {
	ret := _m.Called(ctx, cat)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *domain.IncomeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.IncomeCategory) (*domain.IncomeCategory, error)); ok {
		return rf(ctx, cat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.IncomeCategory) *domain.IncomeCategory); ok {
		r0 = rf(ctx, cat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IncomeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.IncomeCategory) error); ok {
		r1 = rf(ctx, cat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, storeID
func (_m *IncomeRepository) Delete(ctx context.Context, id string, storeID string) error {
	ret := _m.Called(ctx, id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, storeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, f
func (_m *IncomeRepository) FindAll(ctx context.Context, f dto.IncomeListFilter) ([]*domain.Income, int, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Income
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.IncomeListFilter) ([]*domain.Income, int, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.IncomeListFilter) []*domain.Income); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.IncomeListFilter) int); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.IncomeListFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *IncomeRepository) FindByID(ctx context.Context, id string) (*domain.Income, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Income, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Income); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByID provides a mock function with given fields: ctx, id
func (_m *IncomeRepository) GetCategoryByID(ctx context.Context, id string) (*domain.IncomeCategory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *domain.IncomeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.IncomeCategory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.IncomeCategory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IncomeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCategories provides a mock function with given fields: ctx, includeDeleted
func (_m *IncomeRepository) ListCategories(ctx context.Context, includeDeleted bool) ([]*domain.IncomeCategory, error) {
	ret := _m.Called(ctx, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []*domain.IncomeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]*domain.IncomeCategory, error)); ok {
		return rf(ctx, includeDeleted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []*domain.IncomeCategory); ok {
		r0 = rf(ctx, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.IncomeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDeleteCategory provides a mock function with given fields: ctx, id
func (_m *IncomeRepository) SoftDeleteCategory(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, inc
func (_m *IncomeRepository) Update(ctx context.Context, inc *domain.Income) (*domain.Income, error) {
	ret := _m.Called(ctx, inc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Income) (*domain.Income, error)); ok {
		return rf(ctx, inc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Income) *domain.Income); ok {
		r0 = rf(ctx, inc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Income) error); ok {
		r1 = rf(ctx, inc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SumByDateRange provides a mock function with given fields: ctx, storeID, from, to
func (_m *IncomeRepository) SumByDateRange(ctx context.Context, storeID string, from time.Time, to time.Time) (float64, error) {
	ret := _m.Called(ctx, storeID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumByDateRange")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (float64, error)); ok {
		return rf(ctx, storeID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, storeID, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, storeID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: ctx, id, name, desc, isActive
func (_m *IncomeRepository) UpdateCategory(ctx context.Context, id string, name string, desc string, isActive bool) (*domain.IncomeCategory, error) {
	ret := _m.Called(ctx, id, name, desc, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 *domain.IncomeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (*domain.IncomeCategory, error)); ok {
		return rf(ctx, id, name, desc, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) *domain.IncomeCategory); ok {
		r0 = rf(ctx, id, name, desc, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IncomeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) error); ok {
		r1 = rf(ctx, id, name, desc, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIncomeRepository creates a new instance of IncomeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIncomeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IncomeRepository {
	mock := &IncomeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
