// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// LoyaltyRepository is an autogenerated mock type for the LoyaltyRepository type
type LoyaltyRepository struct {
	mock.Mock
}

// AssignTier provides a mock function with given fields: ctx, customerID, tierID
func (_m *LoyaltyRepository) AssignTier(ctx context.Context, customerID string, tierID string) error {
	ret := _m.Called(ctx, customerID, tierID)

	if len(ret) == 0 {
		panic("no return value specified for AssignTier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, customerID, tierID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EarnPoints provides a mock function with given fields: ctx, customerID, transactionID, points
func (_m *LoyaltyRepository) EarnPoints(ctx context.Context, customerID string, transactionID *string, points float64) (*domain.LoyaltyLedger, error) {
	ret := _m.Called(ctx, customerID, transactionID, points)

	if len(ret) == 0 {
		panic("no return value specified for EarnPoints")
	}

	var r0 *domain.LoyaltyLedger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, float64) (*domain.LoyaltyLedger, error)); ok {
		return rf(ctx, customerID, transactionID, points)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, float64) *domain.LoyaltyLedger); ok {
		r0 = rf(ctx, customerID, transactionID, points)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoyaltyLedger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, float64) error); ok {
		r1 = rf(ctx, customerID, transactionID, points)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBalance provides a mock function with given fields: ctx, customerID
func (_m *LoyaltyRepository) GetBalance(ctx context.Context, customerID string) (float64, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, customerID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerTier provides a mock function with given fields: ctx, customerID
func (_m *LoyaltyRepository) GetCustomerTier(ctx context.Context, customerID string) (*domain.MembershipTier, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerTier")
	}

	var r0 *domain.MembershipTier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.MembershipTier, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.MembershipTier); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MembershipTier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields: ctx, customerID
func (_m *LoyaltyRepository) GetHistory(ctx context.Context, customerID string) ([]*domain.LoyaltyLedger, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []*domain.LoyaltyLedger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.LoyaltyLedger, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.LoyaltyLedger); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.LoyaltyLedger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpendPoints provides a mock function with given fields: ctx, customerID, transactionID, points
func (_m *LoyaltyRepository) SpendPoints(ctx context.Context, customerID string, transactionID *string, points float64) (*domain.LoyaltyLedger, error) {
	ret := _m.Called(ctx, customerID, transactionID, points)

	if len(ret) == 0 {
		panic("no return value specified for SpendPoints")
	}

	var r0 *domain.LoyaltyLedger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, float64) (*domain.LoyaltyLedger, error)); ok {
		return rf(ctx, customerID, transactionID, points)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, float64) *domain.LoyaltyLedger); ok {
		r0 = rf(ctx, customerID, transactionID, points)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoyaltyLedger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, float64) error); ok {
		r1 = rf(ctx, customerID, transactionID, points)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoyaltyRepository creates a new instance of LoyaltyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoyaltyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoyaltyRepository {
	mock := &LoyaltyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
