// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MembershipTierRepository is an autogenerated mock type for the MembershipTierRepository type
type MembershipTierRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *MembershipTierRepository) FindAll(ctx context.Context) ([]*domain.MembershipTier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.MembershipTier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.MembershipTier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.MembershipTier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MembershipTier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MembershipTierRepository) FindByID(ctx context.Context, id string) (*domain.MembershipTier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.MembershipTier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.MembershipTier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.MembershipTier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MembershipTier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMembershipTierRepository creates a new instance of MembershipTierRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipTierRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipTierRepository {
	mock := &MembershipTierRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
