// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PaymentRecordRepository is an autogenerated mock type for the PaymentRecordRepository type
type PaymentRecordRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, record
func (_m *PaymentRecordRepository) Create(ctx context.Context, record domain.PaymentRecord) (*domain.PaymentRecord, error) {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.PaymentRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentRecord) (*domain.PaymentRecord, error)); ok {
		return rf(ctx, record)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentRecord) *domain.PaymentRecord); ok {
		r0 = rf(ctx, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaymentRecord) error); ok {
		r1 = rf(ctx, record)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTermin provides a mock function with given fields: ctx, terminID
func (_m *PaymentRecordRepository) FindByTermin(ctx context.Context, terminID string) ([]*domain.PaymentRecord, error) {
	ret := _m.Called(ctx, terminID)

	if len(ret) == 0 {
		panic("no return value specified for FindByTermin")
	}

	var r0 []*domain.PaymentRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.PaymentRecord, error)); ok {
		return rf(ctx, terminID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.PaymentRecord); ok {
		r0 = rf(ctx, terminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PaymentRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, terminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentRecordRepository creates a new instance of PaymentRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRecordRepository {
	mock := &PaymentRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
