// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// RoleRepository is an autogenerated mock type for the RoleRepository type
type RoleRepository struct {
	mock.Mock
}

// CreateRole provides a mock function with given fields: ctx, role, permissionIDs
func (_m *RoleRepository) CreateRole(ctx context.Context, role *domain.Role, permissionIDs []string) (*domain.Role, error) {
	ret := _m.Called(ctx, role, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Role, []string) (*domain.Role, error)); ok {
		return rf(ctx, role, permissionIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Role, []string) *domain.Role); ok {
		r0 = rf(ctx, role, permissionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Role, []string) error); ok {
		r1 = rf(ctx, role, permissionIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRole provides a mock function with given fields: ctx, id
func (_m *RoleRepository) DeleteRole(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListPermissions provides a mock function with given fields: ctx
func (_m *RoleRepository) ListPermissions(ctx context.Context) ([]*domain.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 []*domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRoles provides a mock function with given fields: ctx
func (_m *RoleRepository) ListRoles(ctx context.Context) ([]*domain.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []*domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRole provides a mock function with given fields: ctx, role, permissionIDs
func (_m *RoleRepository) UpdateRole(ctx context.Context, role *domain.Role, permissionIDs []string) (*domain.Role, error) {
	ret := _m.Called(ctx, role, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 *domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Role, []string) (*domain.Role, error)); ok {
		return rf(ctx, role, permissionIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Role, []string) *domain.Role); ok {
		r0 = rf(ctx, role, permissionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Role, []string) error); ok {
		r1 = rf(ctx, role, permissionIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoleRepository creates a new instance of RoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleRepository {
	mock := &RoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
