// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// StoreRepository is an autogenerated mock type for the StoreRepository type
type StoreRepository struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, us
func (_m *StoreRepository) AddMember(ctx context.Context, us *domain.UserStore) error {
	ret := _m.Called(ctx, us)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserStore) error); ok {
		r0 = rf(ctx, us)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, store
func (_m *StoreRepository) Create(ctx context.Context, store *domain.Store) (*domain.Store, error) {
	ret := _m.Called(ctx, store)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Store
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Store) (*domain.Store, error)); ok {
		return rf(ctx, store)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Store) *domain.Store); ok {
		r0 = rf(ctx, store)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Store)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Store) error); ok {
		r1 = rf(ctx, store)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeactivateMember provides a mock function with given fields: ctx, userID, storeID
func (_m *StoreRepository) DeactivateMember(ctx context.Context, userID string, storeID string) error {
	ret := _m.Called(ctx, userID, storeID)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, storeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *StoreRepository) FindAll(ctx context.Context, filter dto.StoreListFilter) ([]*domain.Store, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Store
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.StoreListFilter) ([]*domain.Store, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.StoreListFilter) []*domain.Store); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Store)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.StoreListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.StoreListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *StoreRepository) FindByID(ctx context.Context, id string) (*domain.Store, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Store
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Store, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Store); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Store)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMember provides a mock function with given fields: ctx, userID, storeID
func (_m *StoreRepository) FindMember(ctx context.Context, userID string, storeID string) (*domain.UserStore, error) {
	ret := _m.Called(ctx, userID, storeID)

	if len(ret) == 0 {
		panic("no return value specified for FindMember")
	}

	var r0 *domain.UserStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserStore, error)); ok {
		return rf(ctx, userID, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserStore); ok {
		r0 = rf(ctx, userID, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMembers provides a mock function with given fields: ctx, storeID
func (_m *StoreRepository) ListMembers(ctx context.Context, storeID string) ([]*domain.StoreMember, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []*domain.StoreMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.StoreMember, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.StoreMember); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StoreMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *StoreRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, store
func (_m *StoreRepository) Update(ctx context.Context, store *domain.Store) (*domain.Store, error) {
	ret := _m.Called(ctx, store)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Store
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Store) (*domain.Store, error)); ok {
		return rf(ctx, store)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Store) *domain.Store); ok {
		r0 = rf(ctx, store)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Store)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Store) error); ok {
		r1 = rf(ctx, store)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMemberRole provides a mock function with given fields: ctx, userID, storeID, roleID
func (_m *StoreRepository) UpdateMemberRole(ctx context.Context, userID string, storeID string, roleID string) error {
	ret := _m.Called(ctx, userID, storeID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, storeID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStoreRepository creates a new instance of StoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreRepository {
	mock := &StoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
