// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	dto "github.com/moedahpos/backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// SupplierRepository is an autogenerated mock type for the SupplierRepository type
type SupplierRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, s
func (_m *SupplierRepository) Create(ctx context.Context, s *domain.Supplier) (*domain.Supplier, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Supplier) (*domain.Supplier, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Supplier) *domain.Supplier); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Supplier) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *SupplierRepository) FindAll(ctx context.Context, filter dto.SupplierListFilter) ([]*domain.Supplier, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Supplier
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SupplierListFilter) ([]*domain.Supplier, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SupplierListFilter) []*domain.Supplier); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SupplierListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.SupplierListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *SupplierRepository) FindByID(ctx context.Context, id string) (*domain.Supplier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Supplier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Supplier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *SupplierRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, s
func (_m *SupplierRepository) Update(ctx context.Context, s *domain.Supplier) (*domain.Supplier, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Supplier) (*domain.Supplier, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Supplier) *domain.Supplier); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Supplier) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSupplierRepository creates a new instance of SupplierRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupplierRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupplierRepository {
	mock := &SupplierRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
