// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/moedahpos/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TerminRepository is an autogenerated mock type for the TerminRepository type
type TerminRepository struct {
	mock.Mock
}

// CreateSchedule provides a mock function with given fields: ctx, poID, termins
func (_m *TerminRepository) CreateSchedule(ctx context.Context, poID string, termins []domain.POTermin) error {
	ret := _m.Called(ctx, poID, termins)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.POTermin) error); ok {
		r0 = rf(ctx, poID, termins)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DebtSummary provides a mock function with given fields: ctx, poID, totalAmount
func (_m *TerminRepository) DebtSummary(ctx context.Context, poID string, totalAmount float64) (*domain.PODebtSummary, error) {
	ret := _m.Called(ctx, poID, totalAmount)

	if len(ret) == 0 {
		panic("no return value specified for DebtSummary")
	}

	var r0 *domain.PODebtSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) (*domain.PODebtSummary, error)); ok {
		return rf(ctx, poID, totalAmount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) *domain.PODebtSummary); ok {
		r0 = rf(ctx, poID, totalAmount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PODebtSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64) error); ok {
		r1 = rf(ctx, poID, totalAmount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, terminID
func (_m *TerminRepository) FindByID(ctx context.Context, terminID string) (*domain.POTermin, error) {
	ret := _m.Called(ctx, terminID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.POTermin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.POTermin, error)); ok {
		return rf(ctx, terminID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.POTermin); ok {
		r0 = rf(ctx, terminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.POTermin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, terminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPO provides a mock function with given fields: ctx, poID
func (_m *TerminRepository) FindByPO(ctx context.Context, poID string) ([]*domain.POTermin, error) {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPO")
	}

	var r0 []*domain.POTermin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.POTermin, error)); ok {
		return rf(ctx, poID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.POTermin); ok {
		r0 = rf(ctx, poID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.POTermin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, terminID
func (_m *TerminRepository) UpdateStatus(ctx context.Context, terminID string) error {
	ret := _m.Called(ctx, terminID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, terminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTerminRepository creates a new instance of TerminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerminRepository {
	mock := &TerminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
